# 🔢 50 Pandas + NumPy Integration Practice Questions

> **Instructions:** Each question requires both **Pandas** and
> **NumPy**. Focus on interoperability, vectorized operations, and
> building ML-ready datasets.  
> **Do NOT look at solutions** — hints are provided to guide your
> thinking.  
> Recommended pace: 5–10 questions per day

------------------------------------------------------------------------

## 🔹 NP1–NP10: Array Conversions & Basic Integration

------------------------------------------------------------------------

### NP1. Create a NumPy array and convert it to a Pandas Series.

> 💡 **Hint:** `np.array([...])` creates the array. Pass it directly to
> `pd.Series(array, index=[...], name="...")`.

In [2]:
import pandas as pd
import numpy as np

In [5]:
arr1 = np.array([1,2,3,4,5,6])
pd.Series(arr1, index=['a','b','c','d','e','f'],name="numbers")

a    1
b    2
c    3
d    4
e    5
f    6
Name: numbers, dtype: int64

------------------------------------------------------------------------

### NP2. Convert a 2D NumPy array to a Pandas DataFrame.

> 💡 **Hint:** `pd.DataFrame(np_2d_array, columns=[...])` — shape
> `(n, m)` gives `n` rows and `m` columns.

In [7]:
arr2 = np.array([[1,'Raj'],[2,'Sagar'],[3,'Mahesh'],[4,'Soham'],[5,'Aman']])
pd.DataFrame(arr2, columns=['no','name'])

  no    name
0  1     Raj
1  2   Sagar
2  3  Mahesh
3  4   Soham
4  5    Aman

------------------------------------------------------------------------

### NP3. Generate a random dataset using NumPy and store it in a DataFrame.

> 💡 **Hint:** Use `np.random.seed()` for reproducibility. Try
> `np.random.randn(n, m)` for normal distribution or
> `np.random.randint(lo, hi, n)` for integers.

In [15]:
np.random.seed(42)
arr31 = np.random.randn(10, 6)
print(pd.DataFrame(arr31))

print('\nanother way: ')
arr32 = np.random.randint(10, 50, 10)
print(pd.DataFrame(arr32))

          0         1         2         3         4         5
0  0.496714 -0.138264  0.647689  1.523030 -0.234153 -0.234137
1  1.579213  0.767435 -0.469474  0.542560 -0.463418 -0.465730
2  0.241962 -1.913280 -1.724918 -0.562288 -1.012831  0.314247
3 -0.908024 -1.412304  1.465649 -0.225776  0.067528 -1.424748
4 -0.544383  0.110923 -1.150994  0.375698 -0.600639 -0.291694
5 -0.601707  1.852278 -0.013497 -1.057711  0.822545 -1.220844
6  0.208864 -1.959670 -1.328186  0.196861  0.738467  0.171368
7 -0.115648 -0.301104 -1.478522 -0.719844 -0.460639  1.057122
8  0.343618 -1.763040  0.324084 -0.385082 -0.676922  0.611676
9  1.031000  0.931280 -0.839218 -0.309212  0.331263  0.975545

another way:
    0
0  43
1  42
2  32
3  33
4  46
5  44
6  49
7  31
8  36
9  44

------------------------------------------------------------------------

### NP4. Perform element-wise operations using NumPy and Pandas.

> 💡 **Hint:** You can apply NumPy ufuncs directly on a Pandas Series:
> `np.sqrt(df["col"])`. The result is a Series.

In [21]:
df4 = pd.DataFrame({
    'value': [3,4,9,121,25,144]
})
np.sqrt(df4['value'])

0     1.732051
1     2.000000
2     3.000000
3    11.000000
4     5.000000
5    12.000000
Name: value, dtype: float64

------------------------------------------------------------------------

### NP5. Apply `np.mean` on DataFrame columns.

> 💡 **Hint:** `np.mean(df["col"])` works the same as
> `df["col"].mean()`. Apply to the `.values` array for pure NumPy speed:
> `np.mean(df["col"].values)`.

In [42]:
df5 = pd.DataFrame({
    'value': [3,4,9,121,25,144]
})

mean_series = df4["value"].mean()
mean_numpy = np.mean(df4["value"].values)

print(f"Series Mean: {mean_series}")
print(f"NumPy Array Mean: {mean_numpy}")

Series Mean: 51.0
NumPy Array Mean: 51.0

------------------------------------------------------------------------

### NP6. Replace values using `np.where`.

> 💡 **Hint:** `np.where(condition, value_if_true, value_if_false)` —
> assign the result back to a column:
> `df["col"] = np.where(df["col"] > 50, "High", "Low")`.

In [44]:
df6 = pd.DataFrame({
    'value': [3,4,9,121,25,144]
})

df6['result'] = np.where(df6['value'] > 50,'High','Low')
df6

   value result
0      3    Low
1      4    Low
2      9    Low
3    121   High
4     25    Low
5    144   High

------------------------------------------------------------------------

### NP7. Apply logarithmic transformation using `np.log`.

> 💡 **Hint:** `df["col_log"] = np.log(df["col"])`. Note: `np.log(0)`
> returns `-inf`. Use `np.log1p(x)` which computes `log(1 + x)` to
> safely handle zeros.

In [51]:
df7 = pd.DataFrame({
    'value': [3,4,9,15,25,144]
})

df7['log'] = np.log(df6['value'])
df7['log1p'] = np.log1p(df6['value'])
df7

   value       log     log1p
0      3  1.098612  1.386294
1      4  1.386294  1.609438
2      9  2.197225  2.302585
3     15  2.708050  2.772589
4     25  3.218876  3.258097
5    144  4.969813  4.976734

------------------------------------------------------------------------

### NP8. Apply square root transformation using `np.sqrt`.

> 💡 **Hint:** `df["col_sqrt"] = np.sqrt(df["col"])`. Values must be
> non-negative; use `np.clip(df["col"], 0, None)` first if negatives are
> possible.

In [56]:
df8 = pd.DataFrame({
    'value': [4,-9,16,-25,144]
})

df8['col_sqrt'] = np.sqrt(np.clip(df8['value'],0,None))
df8

   value  col_sqrt
0      4       2.0
1     -9       0.0
2     16       4.0
3    -25       0.0
4    144      12.0

------------------------------------------------------------------------

### NP9. Use NumPy functions inside `apply()`.

> 💡 **Hint:** `df["col"].apply(lambda x: np.log(x))` — or pass the
> NumPy function directly: `df["col"].apply(np.log)`.

In [59]:
df8["log_values"] = df8["value"].apply(np.log)

print(df8)

   value  col_sqrt  log_values
0      4       2.0    1.386294
1     -9       0.0         NaN
2     16       4.0    2.772589
3    -25       0.0         NaN
4    144      12.0    4.969813

------------------------------------------------------------------------

### NP10. Perform broadcasting in a DataFrame using NumPy.

> 💡 **Hint:** Extract `.values` (a 2D NumPy array) and multiply by a
> weights array: `df[cols].values @ weights_array`. The result can be
> assigned back as a new column.

In [12]:
df10 = pd.DataFrame({
    'math': [80, 90, 80],
    'science': [85, 75, 95],
    'english': [90, 88, 82]
})

cols = ['math', 'science', 'english']
weights = np.array([0.4, 0.35, 0.25])

df10['weighted_score'] = df10[cols].values @ weights

print(df10)

   math  science  english  weighted_score
0    80       85       90           84.25
1    90       75       88           84.25
2    80       95       82           85.75

------------------------------------------------------------------------

## 🔹 NP11–NP20: Data Filtering, Transformation & Statistics

------------------------------------------------------------------------

### NP11. Filter DataFrame rows using a NumPy boolean mask.

> 💡 **Hint:** `mask = np.array(df["col"]) > threshold` creates a NumPy
> boolean array. Use `df[mask]` to filter.

In [13]:
print('original data:')
print(df10)

mask = np.array(df10["science"]) > 80
print('\nafter filter: \n',df10[mask])

original data:
   math  science  english  weighted_score
0    80       85       90           84.25
1    90       75       88           84.25
2    80       95       82           85.75

after filter:
    math  science  english  weighted_score
0    80       85       90           84.25
2    80       95       82           85.75

------------------------------------------------------------------------

### NP12. Count non-zero values in a column using NumPy.

> 💡 **Hint:** `np.count_nonzero(df["col"].values)` or
> `np.count_nonzero(df["col"].values != 0)`.

In [15]:
print('original data:')
print(df10)
print('\ncount non-zero values: ',np.count_nonzero(df10["science"].values))

original data:
   math  science  english  weighted_score
0    80       85       90           84.25
1    90       75       88           84.25
2    80       95       82           85.75

count non-zero values:  3

------------------------------------------------------------------------

### NP13. Find unique values using `np.unique`.

> 💡 **Hint:** `np.unique(df["col"])` returns sorted unique values. Use
> `return_counts=True` to also get the frequency of each unique value.

In [23]:
print('original data:')
print(df10)

unique_cnt = np.unique(df10['math'], return_counts=True)
print('\nunique values: ',unique_cnt[0])
print('values count: ',unique_cnt[1])

original data:
   math  science  english  weighted_score
0    80       85       90           84.25
1    90       75       88           84.25
2    80       95       82           85.75

unique values:  [80 90]
values count:  [2 1]

------------------------------------------------------------------------

### NP14. Flatten DataFrame values to a 1D NumPy array.

> 💡 **Hint:** `df[["col1","col2"]].values.flatten()` — the `.flatten()`
> method converts the 2D array to 1D row-by-row.

In [27]:
print('original data:')
print(df10)

convert = df10[['math','science']].values.flatten()
print('\nconvet 2D in 1D: ',convert)

original data:
   math  science  english  weighted_score
0    80       85       90           84.25
1    90       75       88           84.25
2    80       95       82           85.75

convet 2D in 1D:  [80 85 90 75 80 95]

------------------------------------------------------------------------

### NP15. Reshape a NumPy array before creating a DataFrame.

> 💡 **Hint:** `np.arange(1, 25).reshape(6, 4)` creates a 6×4 array.
> Pass directly to `pd.DataFrame(arr, columns=[...])`.

In [32]:
arr15 = np.arange(1, 25).reshape(6,4)
df15 = pd.DataFrame(arr15, columns=['A','B','C','D'])
df15

    A   B   C   D
0   1   2   3   4
1   5   6   7   8
2   9  10  11  12
3  13  14  15  16
4  17  18  19  20
5  21  22  23  24

------------------------------------------------------------------------

### NP16. Perform matrix multiplication using `np.dot`.

> 💡 **Hint:** `np.dot(A, B)` or `A @ B`. Extract `.values` from
> DataFrames first, then wrap the result in a new
> `pd.DataFrame(result, columns=[...])`.

In [41]:
df_A = pd.DataFrame([[1, 2], [3, 4]])
df_B = pd.DataFrame([[5, 6], [7, 8]])

result_matrix = np.dot(df_A.values, df_B.values)

df_result = pd.DataFrame(result_matrix, columns=['A','B'])

print(df_result)

    A   B
0  19  22
1  43  50

------------------------------------------------------------------------

### NP17. Normalize data using NumPy (Min-Max scaling).

> 💡 **Hint:** `arr = df[cols].values` then
> `(arr - arr.min(axis=0)) / (arr.max(axis=0) - arr.min(axis=0))`. Use
> `axis=0` to operate column-wise.

In [46]:
print('original col: ')
print(df15['B'])

arr = df15['B'].values
print('\nnormalized data: ')
print((arr - arr.min(axis=0)) / (arr.max(axis=0) - arr.min(axis=0)))

original col:
0     2
1     6
2    10
3    14
4    18
5    22
Name: B, dtype: int64

normalized data:
[0.  0.2 0.4 0.6 0.8 1. ]

------------------------------------------------------------------------

### NP18. Standardize data using Z-score with NumPy.

> 💡 **Hint:** `z = (arr - arr.mean(axis=0)) / arr.std(axis=0)`. Wrap
> the result in a DataFrame using the original column names.

In [22]:
df18 = pd.DataFrame({
    'value': [1,2,3,4,5,6]
})

arr = df18['value'].values
df18['z-score'] = (arr - arr.mean(axis=0)) / arr.std(axis=0)
df18

   value  z-score
0      1 -1.46385
1      2 -0.87831
2      3 -0.29277
3      4  0.29277
4      5  0.87831
5      6  1.46385

------------------------------------------------------------------------

### NP19. Clip values using `np.clip`.

> 💡 **Hint:**
> `np.clip(df["col"].values, a_min=lower_bound, a_max=upper_bound)` —
> values outside the range are replaced by the boundary values.

In [8]:
df19 = pd.DataFrame({
    'value': [1,2,10,4,30,6]
})

np.clip(df19['value'].values,a_min=5, a_max=10)

array([ 5,  5, 10,  5, 10,  6])

------------------------------------------------------------------------

### NP20. Handle missing values using NumPy.

> 💡 **Hint:** Detect NaN with `np.isnan(arr)`. Fill using
> `np.nanmean(arr)` to compute the mean ignoring NaN, then replace:
> `arr[np.isnan(arr)] = np.nanmean(arr)`.

In [9]:
arr20 = np.array([55,np.nan,77,np.nan,90,np.nan])
mean = np.nanmean(arr20)
arr20[np.isnan(arr20)] = np.nanmean(arr20)

print('mean: ',mean)
print('after replace mean: ',arr20)

mean:  74.0
after replace mean:  [55. 74. 77. 74. 90. 74.]

-----------------------------------------------------------------------

## 🔹 NP21–NP30: Performance, Sorting & Statistical Analysis

------------------------------------------------------------------------

### NP21. Compare NumPy vs Pandas performance on a large array.

> 💡 **Hint:** Use `time.time()` before and after each operation. Apply
> the same computation (`arr * 2 + 1`) to a raw NumPy array and a Pandas
> Series. NumPy is typically faster on pure numeric operations.

In [19]:
import time

arr21 = np.array([21,12,31,13,14,41])

a_start = time.time()
result = arr21 * 2 + 1
a_time = a_start - time.time()
print('numpy array: ',a_time)

s21 = pd.Series([22,34,56,78,34,12])

p_start = time.time()
result = s21 * 2 + 1
p_time = p_start - time.time()
print('pandas series: ',p_time)

numpy array:  -8.7738037109375e-05
pandas series:  -0.0002601146697998047

------------------------------------------------------------------------

### NP22. Calculate cumulative sum using NumPy.

> 💡 **Hint:** `np.cumsum(df["col"].values)` — assign back:
> `df["cum_col"] = np.cumsum(df["col"])`.

In [25]:
df22 = pd.DataFrame({
    'value': [1,2,3,4,5,6]
})
df22['cum_col'] = np.cumsum(df22['value'])
df22

   value  cum_col
0      1        1
1      2        3
2      3        6
3      4       10
4      5       15
5      6       21

------------------------------------------------------------------------

### NP23. Use `np.argmax` and `np.argmin`.

> 💡 **Hint:** `np.argmax(df["col"].values)` returns the **integer
> position** of the maximum. Use `df.iloc[idx]` or `df.loc[idx]` to
> retrieve the full row.

In [39]:
df23 = pd.DataFrame({
    'value': [1,2,3,4,5,6]
})
idx = np.argmax(df23['value'].values)
print(df23.iloc[[5]])

   value
5      6

------------------------------------------------------------------------

### NP24. Sort values using NumPy `np.argsort`.

> 💡 **Hint:** `sorted_idx = np.argsort(df["col"].values)` gives indices
> that would sort the array. Use `df.iloc[sorted_idx]` to reorder the
> DataFrame.

In [ ]:
df23 = pd.DataFrame({
    'value': [1,4,5,6,2,3]
})
print('original:')
print(df23)

sorted_idx = np.argsort(df23['value'].values)
print('\nreorder: \n',df23.iloc[sorted_idx])

original:
   value
0      1
1      4
2      5
3      6
4      2
5      3

reorder:
    value
0      1
4      2
5      3
1      4
2      5
3      6

------------------------------------------------------------------------

### NP25. Compute correlation using `np.corrcoef`.

> 💡 **Hint:** `np.corrcoef([df["col1"].values, df["col2"].values])`
> returns a 2×2 correlation matrix. Wrap in a DataFrame for readability.
> Compare with `df.corr()`.

In [61]:
df25 = pd.DataFrame({
    'col1': [1,2,3,4,5,6],
    'col2':[45,67,23,78,90,67]
})

print("--- NumPy Correlation DataFrame ---")
arr25 = np.corrcoef([df25['col1'].values,df25['col2'].values])
np_arr_df = pd.DataFrame(arr25, columns=['col1','col2'])
print(np_arr_df)

print("\n--- Pandas df.corr() Matrix ---")
print(df25[['col1','col2']].corr())

--- NumPy Correlation DataFrame ---
       col1      col2
0  1.000000  0.519419
1  0.519419  1.000000

--- Pandas df.corr() Matrix ---
          col1      col2
col1  1.000000  0.519419
col2  0.519419  1.000000

-----------------------------------------------------------------------

### NP26. Detect NaN values using NumPy.

> 💡 **Hint:** `np.isnan(arr)` returns a boolean array. Count NaN with
> `np.isnan(arr).sum()`. Compare with `pd.isnull(series)`.

In [66]:
arr26 = np.array([29,np.nan,60,np.nan,34])
bool_arr = np.isnan(arr26)
print("--- NumPy array ---")
print("Total NaN count:",np.isnan(arr26).sum())

s26 = pd.Series([45,56,np.nan,56,34])
print("\n--- Pandas series ---")
print("Total missing count:",pd.isnull(s26).sum())

--- NumPy array ---
Total NaN count: 2

--- Pandas series ---
Total missing count: 1

------------------------------------------------------------------------

### NP27. Create boolean masks using NumPy.

> 💡 **Hint:**
> `mask = (np.array(df["col1"]) > 80) & (np.array(df["col2"]) < 40)` —
> use `df[mask]` to filter.

In [69]:
df27 = pd.DataFrame({
    'col1': [1,2,3,4,5,6],
    'col2':[45,67,23,78,90,67]
})

msk = (np.array(df27['col1']) > 3) & (np.array(df27['col2']) < 65)
print('boolean mask: ',msk)

boolean mask:  [False False False False False False]

------------------------------------------------------------------------

### NP28. Apply logical operations (`np.logical_and`, `np.logical_or`, `np.logical_not`).

> 💡 **Hint:** `np.logical_and(cond1, cond2)` is equivalent to
> `cond1 & cond2`. These functions work on NumPy arrays; convert Series
> with `.values` first.

In [ ]:
df28 = pd.DataFrame({
    'A': [1, 6, 3, 8, 5],
    'B': [10, 20, 30, 40, 50]
})

arr1 = df28['A'].values
arr2 = df28['B'].values
print('\n--- using numpy function: ---')
print(df28[np.logical_and(arr1 > 4,arr2 < 50)])
print('\n--- using bitwise and: ---')
print(df28[(arr1 > 4) & (arr2 < 50)])

--- using numpy function: ---
   A   B
1  6  20
3  8  40

--- using bitwise and: ---
   A   B
1  6  20
3  8  40

------------------------------------------------------------------------

### NP29. Apply `np.select` for multi-condition assignment.

> 💡 **Hint:**
> `df["Grade"] = np.select([df["Score"] >= 90, df["Score"] >= 75], ["A","B"], default="C")`
> — conditions are checked in order; the first match wins.

In [ ]:
df29 = pd.DataFrame({
    'score': [45,67,89,67,34,90]
})

df29['Grade'] = np.select([df29['score'] >= 90, df29['score'] >= 75], ['A','B'], default='C') #np.select() is used to assign values based on multiple conditions.
print('multi-condition assignment: ')
print(df29['Grade'])

multi-condition assignment:
0    C
1    C
2    B
3    C
4    C
5    A
Name: Grade, dtype: str

------------------------------------------------------------------------

### NP30. Multiply DataFrame columns element-wise using NumPy.

> 💡 **Hint:** `np.multiply(df["col1"].values, df["col2"].values)` is
> equivalent to `df["col1"] * df["col2"]` but uses NumPy internally.

In [102]:
print('original data: ')
print(df28)

print('\nnumpy multiplcations: ')
print(np.multiply(df28['A'].values, df28['B'].values))
print('\npandas multiplcations: ')
print(df28['A'] * df28['B'])

original data:
   A   B
0  1  10
1  6  20
2  3  30
3  8  40
4  5  50

numpy multiplcations:
[ 10 120  90 320 250]

pandas multiplcations:
0     10
1    120
2     90
3    320
4    250
dtype: int64

------------------------------------------------------------------------

## 🔹 NP31–NP40: Data Wrangling & Conversion

------------------------------------------------------------------------

### NP31. Shuffle dataset rows using NumPy.

> 💡 **Hint:** `shuffled_idx = np.random.permutation(df.index)` creates
> a random permutation of row indices. Use
> `df.loc[shuffled_idx].reset_index(drop=True)`.

In [ ]:
print('original data: ')
print(df28)

shuffled_idx = np.random.permutation(df28.index) #shuffle indices
df28.iloc[shuffled_idx].reset_index(drop=True) #rearranges the rows according to those shuffled indices.

original data:
   A   B
0  1  10
1  6  20
2  3  30
3  8  40
4  5  50

   A   B
0  1  10
1  5  50
2  8  40
3  3  30
4  6  20

------------------------------------------------------------------------

### NP32. Sample random rows using NumPy.

> 💡 **Hint:**
> `sample_idx = np.random.choice(df.index, size=N, replace=False)` — use
> `df.loc[sample_idx]`. Compare with `df.sample(N)`.

In [111]:
print('original data: ')
print(df28)

sample_idx = np.random.choice(df28.index, size=3, replace=False)
print('\n--- NumPy random sample: ---')
print(df28.iloc[sample_idx])

print('\n--- Pandas random sample: ---')
print(df28.sample(3))

original data:
   A   B
0  1  10
1  6  20
2  3  30
3  8  40
4  5  50

--- NumPy random sample: ---
   A   B
0  1  10
2  3  30
4  5  50

--- Pandas random sample: ---
   A   B
3  8  40
2  3  30
4  5  50

------------------------------------------------------------------------

### NP33. Calculate percentiles using NumPy.

> 💡 **Hint:** `np.percentile(df["col"].values, [25, 50, 75])` returns
> Q1, median, Q3. Use `np.percentile(arr, p)` for any percentile p in
> \[0, 100\].

In [119]:
print('original data: ')
print(df28)

arr33 = df28['A'].values
q1,median,q3 = np.percentile(arr33, [25,50,75])
print(f'\nQ1: {q1}\nQ2: {median}\nQ3: {q3}')

original data:
   A   B
0  1  10
1  6  20
2  3  30
3  8  40
4  5  50

Q1: 3.0
Q2: 5.0
Q3: 6.0

------------------------------------------------------------------------

### NP34. Calculate variance and standard deviation.

> 💡 **Hint:** `np.var(arr)` and `np.std(arr)` use `ddof=0`
> (population). Pandas `.var()` and `.std()` use `ddof=1` (sample). Be
> aware of this difference when comparing results.

ddof=0 → divide by N (population) → NumPy default.

ddof=1 → divide by N − 1 (sample, Bessel's correction) → pandas default.

That's why np.var() and Series.var() may return different results for the same data.

In [ ]:
print('original data: ')
print(df28)

arr = df28['A'].values
print('\n--- NumPy variance and standard deviation: ---')
print('var: ',np.var(arr,ddof=0))   #Delta Degrees of Freedom.  Population variance/std
print('std: ',np.std(arr,ddof=0))
print('\n--- Pandas variance and standard deviation: ---')
print('var: ',df28['A'].var(ddof=1))    #Sample variance/std
print('std: ',df28['A'].std(ddof=1))

original data:
   A   B
0  1  10
1  6  20
2  3  30
3  8  40
4  5  50

--- NumPy variance and standard deviation: ---
var:  5.84
std:  2.4166091947189146

--- Pandas variance and standard deviation: ---
var:  7.3
std:  2.701851217221259

------------------------------------------------------------------------

### NP35. Replace a DataFrame column with a NumPy array.

> 💡 **Hint:** `df["col"] = new_numpy_array` — the array length must
> match the number of rows. NumPy arrays are accepted directly.

In [127]:
print('original data: ')
print(df28)

df28['A'] = [11,22,33,44,55]
print('\nafter replace dataframe col:')
print(df28)

original data:
    A   B
0  11  10
1  22  20
2  33  30
3  44  40
4  55  50

after replace dataframe col:
    A   B
0  11  10
1  22  20
2  33  30
3  44  40
4  55  50

------------------------------------------------------------------------

### NP36. Convert DataFrame to NumPy using `to_numpy()`.

> 💡 **Hint:** `df[["col1","col2"]].to_numpy()` returns a 2D NumPy
> array. This is the preferred method over `.values` as it accepts
> `dtype` and `na_value` parameters.

In [134]:
print('original data: ')
print(df28)
arr36 = df28[['A','B']].to_numpy()
print('\nconvert dataframe in 2D numpy: ')
print(arr36)
print('\ntype: ',type(arr36))

original data:
    A   B
0  11  10
1  22  20
2  33  30
3  44  40
4  55  50

convert dataframe in 2D numpy:
[[11 10]
 [22 20]
 [33 30]
 [44 40]
 [55 50]]

type:  <class 'numpy.ndarray'>

------------------------------------------------------------------------

### NP37. Compare `.values` vs `.to_numpy()`.

> 💡 **Hint:** Both return a NumPy array. Key difference:
> `.to_numpy(dtype=np.float32)` accepts a `dtype` argument for explicit
> casting. Use `np.array_equal(a, b)` to confirm they produce the same
> result.

.values → simple conversion to a NumPy array.

.to_numpy(dtype=...) → allows explicit dtype conversion and additional options.

In [ ]:
print('original data: ')
print(df28)

arr1 = df28.values
print('\n--- dataframe attribute: ---')
print(arr1)

arr2 = df28.to_numpy(dtype=np.float32)
print('\n--- numpy function: ---')
print(arr2)

print('\nsame result: ',np.array_equal(arr1,arr2))  #np.array_equal() compares the values and shape, not the dtype.

original data:
    A   B
0  11  10
1  22  20
2  33  30
3  44  40
4  55  50

--- dataframe attribute: ---
[[11 10]
 [22 20]
 [33 30]
 [44 40]
 [55 50]]

--- numpy function: ---
[[11. 10.]
 [22. 20.]
 [33. 30.]
 [44. 40.]
 [55. 50.]]

same result:  True

------------------------------------------------------------------------

### NP38. Slice a column using NumPy array indexing.

> 💡 **Hint:** Extract with `.values`, then apply NumPy slicing:
> `arr[::2]` (every other element), `arr[::-1]` (reversed),
> `arr[[0,3,5]]` (fancy indexing).

In [153]:
df38 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5,6],
    'B': [10, 20, 30, 40, 50,66]
})

arr38 = df38.values
print('every other element: \n',arr38[::2])
print('\nreversed: \n',arr38[::-1])
print('\nfancy indexing: \n',arr38[[0,3,5]])

every other element:
 [[ 1 10]
 [ 3 30]
 [ 5 50]]

reversed:
 [[ 6 66]
 [ 5 50]
 [ 4 40]
 [ 3 30]
 [ 2 20]
 [ 1 10]]

fancy indexing:
 [[ 1 10]
 [ 4 40]
 [ 6 66]]

------------------------------------------------------------------------

### NP39. Merge NumPy-generated data into a DataFrame.

> 💡 **Hint:** Create two DataFrames from NumPy arrays with a common key
> column (e.g., `ID`). Use `pd.merge(df1, df2, on="ID", how="outer")`.

In [159]:
arr391 = np.array([[1,10],[2,20],[3,30],[4,40],[5,50]])
arr392 = np.array([[1,100],[2,200],[3,300],[4,400],[5,500]])

df391 = pd.DataFrame(arr391, columns=['id','value1'])
print('Dataframe 1: \n',df391)
df392 = pd.DataFrame(arr392, columns=['id','value2'])
print('\nDataframe 2: \n',df392)

pd.merge(df391,df392, on='id', how='outer')

Dataframe 1:
    id  value1
0   1      10
1   2      20
2   3      30
3   4      40
4   5      50

Dataframe 2:
    id  value2
0   1     100
1   2     200
2   3     300
3   4     400
4   5     500

   id  value1  value2
0   1      10     100
1   2      20     200
2   3      30     300
3   4      40     400
4   5      50     500

------------------------------------------------------------------------

### NP40. Apply rolling computation using NumPy.

> 💡 **Hint:** Use a list comprehension:
> `[np.mean(arr[max(0,i-w+1):i+1]) for i in range(len(arr))]` to
> manually compute a rolling mean with window `w`. Compare with
> `df["col"].rolling(w).mean()`.

A rolling mean (or moving average) is the average of the last w values, where w is the window size.

* Pandas gives NaN for the first two positions because it waits until it has a full window of 3 values.

* A rolling mean is a moving average computed over a fixed-size sliding window of recent values.

In [ ]:
print('Original data:')
print(df38)

arr = df38['A'].values
w = 3

print('\nNumPy rolling mean:')
rolling_mean = [float(np.mean(arr[max(0, i-w+1):i+1])) for i in range(len(arr))]  # float use becoz get np.float64(...) objects.
print(rolling_mean)

print('\nPandas rolling mean:')
print(df38['A'].rolling(w).mean())

Original data:
   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50
5  6  66

NumPy rolling mean:
[1.0, 1.5, 2.0, 3.0, 4.0, 5.0]

Pandas rolling mean:
0    NaN
1    NaN
2    2.0
3    3.0
4    4.0
5    5.0
Name: A, dtype: float64

------------------------------------------------------------------------

## 🔹 NP41–NP50: ML-Ready Dataset Preparation

------------------------------------------------------------------------

### NP41. Create a synthetic ML dataset using NumPy.

> 💡 **Hint:** Use `np.random.normal`, `np.random.randint`,
> `np.random.choice` to generate features. Use `np.where` or `np.select`
> to create a binary/multi-class label column.

In [ ]:
df = pd.DataFrame({
    'age': np.random.randint(18, 60, 10),
    'salary': np.random.normal(50000, 10000, 10),
    'city': np.random.choice(['Mumbai', 'Pune', 'Delhi'], 10)
})

# Binary label
df['purchased'] = np.where(df['salary'] > 50000, 1, 0)

#For a multi-class label:
conditions = [df['salary'] < 40000,df['salary'] < 60000,df['salary'] >= 60000]
df['income_level'] = np.select(conditions, ['Low', 'Medium', 'High'], default='unknown')

print(df)

   age        salary    city  purchased income_level
0   57  50959.944410    Pune          1       Medium
1   30  42359.420613  Mumbai          0       Medium
2   30  51123.086856    Pune          1       Medium
3   42  37675.822436   Delhi          0          Low
4   24  42868.342376   Delhi          0       Medium
5   40  62967.742393  Mumbai          1         High
6   56  43934.497617  Mumbai          0       Medium
7   38  61985.660969    Pune          1         High
8   43  19087.767376   Delhi          0          Low
9   28  42310.690366    Pune          0       Medium

------------------------------------------------------------------------

### NP42. Detect and replace outliers using NumPy.

> 💡 **Hint:** Compute Q1, Q3 with `np.percentile`. Define bounds as
> `Q1 - 1.5*IQR` and `Q3 + 1.5*IQR`. Use `np.clip(arr, lo, hi)` to
> replace outliers with boundary values.

In [185]:
arr42 = np.array([-500, 12, -45, 67, 155, 23, 70, 100, 500])
q1 = np.percentile(arr42,25)
q3 = np.percentile(arr42,75)
iqr = q3 - q1
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr
clapped = np.clip(arr42, lower_bound, upper_bound)
print('original arr: ', arr42)
print('lower_bound: ',lower_bound)
print('upper_bound: ',upper_bound)
print('after clapped: ',clapped)

original arr:  [-500   12  -45   67  155   23   70  100  500]
lower_bound:  -120.0
upper_bound:  232.0
after clapped:  [-120.   12.  -45.   67.  155.   23.   70.  100.  232.]

------------------------------------------------------------------------

### NP43. Scale dataset using NumPy functions.

> 💡 **Hint:** Apply Min-Max or Z-score scaling using NumPy on the
> `.values` array. Store results as new columns in the DataFrame.

* Min-Max Scaling: rescales values to the range [0, 1].
* Z-Score Scaling: rescales values to have mean = 0 and standard deviation = 1.

In [186]:
print('Original data:')
print(df38)

arr38 = df38['A'].values

# Min-Max Scaling
df38['A_minmax'] = (arr38 - np.min(arr38)) / (np.max(arr38) - np.min(arr38))

# Z-Score Scaling
df38['A_zscore'] = (arr38 - np.mean(arr38)) / np.std(arr38)

print('\nScaled data:')
print(df38)

Original data:
   A   B
0  1  10
1  2  20
2  3  30
3  4  40
4  5  50
5  6  66

Scaled data:
   A   B  A_minmax  A_zscore
0  1  10       0.0  -1.46385
1  2  20       0.2  -0.87831
2  3  30       0.4  -0.29277
3  4  40       0.6   0.29277
4  5  50       0.8   0.87831
5  6  66       1.0   1.46385

------------------------------------------------------------------------

### NP44. Engineer new features using NumPy.

> 💡 **Hint:** Create polynomial features (`np.square`, `np.power`), log
> features (`np.log1p`), interaction features (column1 × column2), and
> binned features (`np.digitize`).

In [196]:
df44 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5, 6],
    'B': [10, 20, 30, 40, 50, 66]
})

arr44 = df44['A'].values

df44['square'] = np.square(arr44)
df44['power'] = np.power(arr44,3)
df44['log1p'] = np.log1p(arr44)
df44['interaction'] = df44['A'].values * df44['B'].values
df44['digitize'] = np.digitize(arr44, bins=[2])   #np.digitize() converts numeric data into categories/bins (discretization) or used to group continuous values into bins (intervals). 
df44

   A   B  square  power     log1p  interaction  digitize
0  1  10       1      1  0.693147           10         0
1  2  20       4      8  1.098612           40         1
2  3  30       9     27  1.386294           90         1
3  4  40      16     64  1.609438          160         1
4  5  50      25    125  1.791759          250         1
5  6  66      36    216  1.945910          396         1

------------------------------------------------------------------------

### NP45. Use exponential functions (`np.exp`).

> 💡 **Hint:** `np.exp(df["col"])` computes `e^x` for each element. This
> is the inverse of `np.log`. Useful for reverting log-transformed
> values.

In [ ]:
df45 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5, 6],
    'B': [10, 20, 30, 40, 50, 66]
})

exp = np.exp(df45['A'])   #np.exp() computes the exponential function, i.e.,
df45['exp'] = exp
df45['log'] = np.log(exp) #np.log() Convert exponential relationships to linear ones. or computes the natural logarithm, i.e., the inverse of np.exp().
df45

   A   B         exp  log
0  1  10    2.718282  1.0
1  2  20    7.389056  2.0
2  3  30   20.085537  3.0
3  4  40   54.598150  4.0
4  5  50  148.413159  5.0
5  6  66  403.428793  6.0

------------------------------------------------------------------------

### NP46. Compute differences using `np.diff`.

> 💡 **Hint:** `np.diff(df["col"].values)` returns an array of
> consecutive differences (length = n−1). Prepend `np.nan` and assign
> back: `df["col_diff"] = np.insert(np.diff(arr), 0, np.nan)`.

In [207]:
df46 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5, 6],
    'B': [10, 20, 30, 40, 50, 66]
})

arr46 = df46['A'].values.astype(float)
df46['A_diff'] = np.insert(np.diff(arr46), 0, np.nan)

print('\nAfter computing differences:')
print(df46)

After computing differences:
   A   B  A_diff
0  1  10     NaN
1  2  20     1.0
2  3  30     1.0
3  4  40     1.0
4  5  50     1.0
5  6  66     1.0

------------------------------------------------------------------------

### NP47. Apply conditional encoding using NumPy.

> 💡 **Hint:** Use `np.select` with a list of conditions and
> corresponding integer codes to encode categorical columns numerically.
> For example: `DS → 0`, `ML → 1`, `AI → 2`.

In [ ]:
df47 = pd.DataFrame({
    'Course': ['DS', 'ML', 'AI', 'DS', 'AI', 'ML', 'PHP']
})

print('Original data:')
print(df47)

conditions = [df47['Course'] == 'DS',df47['Course'] == 'ML',df47['Course'] == 'AI']

df47['Course_Code'] = np.select(conditions, [0, 1, 2], default=-1) #np.select() is used to assign values based on multiple conditions.

print('\nAfter encoding:')
print(df47)

Original data:
  Course
0     DS
1     ML
2     AI
3     DS
4     AI
5     ML
6    PHP

After encoding:
  Course  Course_Code
0     DS            0
1     ML            1
2     AI            2
3     DS            0
4     AI            2
5     ML            1
6    PHP           -1

------------------------------------------------------------------------

### NP48. Build an ML-ready dataset (feature matrix X and label vector y).

> 💡 **Hint:** Select numeric feature columns → call
> `.to_numpy(dtype=np.float32)` → store as `X`. Create a binary label:
> `y = (df["col"] >= threshold).astype(int).to_numpy()`. Check shapes
> with `X.shape` and `y.shape`.

In [215]:
df48 = pd.DataFrame({
    'A': [1, 2, 3, 4, 5, 6],
    'B': [10, 20, 30, 40, 50, 66]
})

# Feature matrix (X)
X = df48[['A','B']].to_numpy(dtype=np.float32)

# Binary label vector (y)
y = (df48['B'] >= 30).astype(int).to_numpy()
print('\nFeature matrix (X):')
print(X)

print('\nLabel vector (y):')
print(y)

print('\nShapes:')
print('X shape:', X.shape)
print('y shape:', y.shape)

Feature matrix (X):
[[ 1. 10.]
 [ 2. 20.]
 [ 3. 30.]
 [ 4. 40.]
 [ 5. 50.]
 [ 6. 66.]]

Label vector (y):
[0 0 1 1 1 1]

Shapes:
X shape: (6, 2)
y shape: (6,)

------------------------------------------------------------------------

### NP49. Perform a mini data analysis project.

> 💡 **Hint:** Follow these steps: (1) Generate data with NumPy, (2)
> Store in DataFrame, (3) Clean with Pandas, (4) Engineer features with
> NumPy, (5) GroupBy analysis, (6) Detect outliers, (7) Export summary.

In [ ]:
#step 1: Generate data with NumPy---------------------------------------------------------------
np.random.seed(42)

age = np.random.randint(18, 60, 100)
sal = np.random.normal(50000, 12000, 100)
dept = np.random.choice(['HR', 'IT', 'Sales', 'Finance'], 100)
exp = np.random.randint(1, 20, 100)

#step 2: Store in DataFrame---------------------------------------------------------------
df49 = pd.DataFrame({'age': age,'sal': sal,'dept': dept,'exp': exp})

#step 3: Clean with Pandas----------------------------------------------------------------
print('check null values: \n',df49.isnull().sum())

df49 = df49.drop_duplicates()

print('\n--------- Cleaned data: ------------')
print(df49.head())

#step 4: Engineer features with NumPy------------------------------------------------------------
# Salary category
df49['salary_level'] = np.where(
    df49['sal'] >= 50000,
    'High',
    'Low'
)

# Experience category
condition = [df49['exp'] < 5, df49['exp'] < 10, df49['exp'] >= 10]
df49['exp_level'] = np.select(condition,['Beginner', 'Intermediate', 'Expert'], default='unknown')
print('\n----------------- After feature engineering: -------------------')
print(df49.head())

#step 5: GroupBy analysis--------------------------------------------------------------------------
# Average salary by department
avg_sal_by_dept = df49.groupby('dept')['sal'].mean()
print('\n----- GroupBy analysis ------')
print('Average salary by department: \n',avg_sal_by_dept)

# Average experience by departmen
avg_exp_by_dept = df49.groupby('dept')['exp'].mean()
print('\nAverage experience by department: \n',avg_exp_by_dept)

# Multiple aggregations
summary = df49.groupby('dept').agg({
    'sal': ['mean', 'min', 'max'],
    'exp': ['mean', 'sum']
})

print('\n---------------------Aggregate Summary: ---------------------------')
print(summary)

#step 6: Detect outliers-------------------------------------------------------------------
arr49 = df49['sal'].values

q1 = np.percentile(arr49, 25)
q3 = np.percentile(arr49, 75)
iqr = q3 - q1

lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr

outliers = df49[(arr49 < lower_bound) | (arr49 > upper_bound)]

print('\nOutliers:')
print(outliers)

#step 7: Export summary----------------------------------------------------------------------

summary.to_csv('department_summary.csv')
print('\nFile saved as department_summary.csv')

check null values:
 age     0
sal     0
dept    0
exp     0
dtype: int64

--------- Cleaned data: ------------
   age           sal     dept  exp
0   56  47981.538943  Finance    6
1   46  63977.223746    Sales    3
2   32  47051.027751    Sales    9
3   25  40763.986716       HR    5
4   38  64546.068106       HR   17

----------------- After feature engineering: -------------------
   age           sal     dept  exp salary_level     exp_level
0   56  47981.538943  Finance    6          Low  Intermediate
1   46  63977.223746    Sales    3         High      Beginner
2   32  47051.027751    Sales    9          Low  Intermediate
3   25  40763.986716       HR    5          Low  Intermediate
4   38  64546.068106       HR   17         High        Expert

----- GroupBy analysis ------
Average salary by department:
 dept
Finance    49636.047835
HR         48380.332801
IT         49877.851987
Sales      53210.407147
Name: sal, dtype: float64

Average experience by department:
 dept
Finance     9.400000
HR          9.958333
IT         11.095238
Sales       9.050000
Name: exp, dtype: float64

---------------------Aggregate Summary: ---------------------------
                  sal                                    exp
                 mean           min           max       mean  sum
dept
Finance  49636.047835  24900.803964  73341.387374   9.400000  329
HR       48380.332801  32396.385378  73206.077611   9.958333  239
IT       49877.851987  20014.890300  75904.742280  11.095238  233
Sales    53210.407147  20363.613619  64801.961655   9.050000  181

Outliers:
Empty DataFrame
Columns: [age, sal, dept, exp, salary_level, exp_level]
Index: []

File saved as department_summary.csv

------------------------------------------------------------------------

### NP50. Build an end-to-end pipeline using NumPy + Pandas.

> 💡 **Hint:** Chain all steps together:  
> 1. `np.random.seed(X)` → generate raw data  
> 2. `np.clip` → clean invalid values  
> 3. `np.log`, `np.square`, `np.where` → feature engineering  
> 4. `df.groupby().agg(...)` → statistical analysis  
> 5. IQR + `np.clip` → outlier removal  
> 6. `df[features].to_numpy(dtype=np.float32)` → ML feature matrix  
> 7. Export with `df.to_csv(...)`

In [ ]:
# Step 1: generate raw data-------------------------------------------------------------
np.random.seed(42)
data = {
    "age": np.random.randint(15, 90, size=100),         
    "salary": np.random.uniform(20000, 150000, size=100),
    "dept": np.random.choice(["Sales", "IT", "HR"], size=100)
}
df = pd.DataFrame(data)

# Step 2: clean invalid values-----------------------------------------------------------
df["age"] = np.clip(df["age"], 18, 65)

# Step 3: Feature engineering using np.log, np.square, and np.where
df["log_salary"] = np.log(df["salary"])
df["age_squared"] = np.square(df["age"])
df["is_senior"] = np.where((df["age"] > 50) & (df["salary"] > 80000), 1, 0)

# Step 4: Statistical analysis using groupby and agg---------------------------------------
dept_summary = df.groupby("dept").agg(
    avg_salary=("salary", "mean"),
    max_age=("age", "max"),
    total_seniors=("is_senior", "sum")
)
print("--- Step 4: Department Summary ---")
print(dept_summary, "\n")

# Step 5: IQR + np.clip ------------------------------------------------------------------------
q1, q3 = np.percentile(df["salary"], [25, 75])
iqr = q3 - q1
lower_bound = q1 - 1.5 * iqr
upper_bound = q3 + 1.5 * iqr
df["salary"] = np.clip(df["salary"], lower_bound, upper_bound)

# Step 6: extract feature matrix (float32 datatype)---------------------------------------------
features = ["age", "salary", "log_salary", "age_squared", "is_senior"]
X = df[features].to_numpy(dtype=np.float32)

print("--- Step 6: ML Feature Matrix Shape ---")
print(f"Matrix shape: {X.shape} | Data type: {X.dtype}\n")

# Step 7: Export final processed DataFrame to CSV-----------------------------------------------
df.to_csv("processed_pipeline_output.csv", index=False)
print("Processed pipeline exported successfully to CSV...")

--- Step 4: Department Summary ---
         avg_salary  max_age  total_seniors
dept
HR     77128.256008       65              7
IT     78271.330258       65              4
Sales  87279.107422       65             15

--- Step 6: ML Feature Matrix Shape ---
Matrix shape: (100, 5) | Data type: float32

Processed pipeline exported successfully to CSV...

------------------------------------------------------------------------

## 🎯 Quick Hints Reference

| Task               | NumPy Function                      | Pandas Equivalent                 |
|------------|---------------------------|----------------------------------|
| Convert to array   | `arr = df["col"].values`            | `arr = df["col"].to_numpy()`      |
| Conditional assign | `np.where(cond, a, b)`              | `df.loc[cond, "col"] = val`       |
| Multi-condition    | `np.select([c1,c2],[v1,v2])`        | `map()` / `pd.cut()`              |
| Clip values        | `np.clip(arr, lo, hi)`              | `df["col"].clip(lo, hi)`          |
| Count NaN          | `np.isnan(arr).sum()`               | `df.isnull().sum()`               |
| Correlation        | `np.corrcoef([a, b])`               | `df.corr()`                       |
| Percentile         | `np.percentile(arr, q)`             | `df["col"].quantile(q/100)`       |
| Cumulative sum     | `np.cumsum(arr)`                    | `df["col"].cumsum()`              |
| Sort indices       | `np.argsort(arr)`                   | `df.sort_values(...).index`       |
| Unique values      | `np.unique(arr)`                    | `df["col"].unique()`              |
| Reshape            | `arr.reshape(r, c)`                 | — (use before DataFrame creation) |
| Min-Max scale      | `(x - x.min()) / (x.max()-x.min())` | Manual or sklearn                 |
| Z-score            | `(x - x.mean()) / x.std()`          | Manual or sklearn                 |

------------------------------------------------------------------------

*📌 Always try solving without hints first.*  
*⭐ Happy Learning NumPy + Pandas — the backbone of every ML project!*