# 🐼 100 Pandas Practical Questions

> **Instructions:** Try to solve each question on your own. Use the hints only if you are stuck.  
> Progress: Basic → Intermediate → Advanced  
> Recommended pace: 10–15 questions per day

------------------------------------------------------------------------

## 🔹 Section 1: Basics & Series (Q1–Q20)

------------------------------------------------------------------------

In [1]:
import pandas as pd

### Q1. Create a Pandas Series from a list of integers.

> 💡 **Hint:** Use `pd.Series([...])`. The default index starts from 0.

In [3]:
s1 = pd.Series([10,20,30,40,50])
print(s1)

0    10
1    20
2    30
3    40
4    50
dtype: int64

------------------------------------------------------------------------

### Q2. Create a Series from a dictionary with custom index.

> 💡 **Hint:** Pass a `dict` to `pd.Series()`. Keys become the index labels automatically.

In [49]:
data_dict = {'A': 50, 'B': 10, 'C': 80, 'D': 30, 'E': 50}
s2 = pd.Series(data_dict)
print(s2)

A    50
B    10
C    80
D    30
E    50
dtype: int64

------------------------------------------------------------------------

### Q3. Access elements using index labels.

> 💡 **Hint:** Use `s["label"]` for a single value, `s[["a","b"]]` for multiple, and `s["a":"c"]` for a range. Label slices are **inclusive** on both ends.

In [18]:
print('single value: ',s2['A'])
print('\nmultiple: \n',s2[['A','C']])
print('\nrange value: \n',s2['A':'C'])

single value:  50

multiple:
 A    50
C    80
dtype: int64

range value:
 A    50
B    10
C    80
dtype: int64

------------------------------------------------------------------------

### Q4. Perform arithmetic operations on a Series.

> 💡 **Hint:** Use `+`, `-`, `*`, `/`, `//`, `%`, `**` directly on the Series. Operations are **element-wise** and **index-aligned**.

In [24]:
print('add: \n',s2 + 10)
print('\nminus: \n',s2 - 5)
print('\nmultiply: \n',s2 * 5)
print('\ndivide: \n',s2 / 10)
print('\ninteger division: \n',s2 // 10)
print('\npower: \n',s2 ** 2)

add:
 A    60
B    20
C    90
D    40
E    60
dtype: int64

minus:
 A    45
B     5
C    75
D    25
E    45
dtype: int64

multiply:
 A    250
B     50
C    400
D    150
E    250
dtype: int64

divide:
 A    5.0
B    1.0
C    8.0
D    3.0
E    5.0
dtype: float64

integer division:
 A    5
B    1
C    8
D    3
E    5
dtype: int64

power:
 A    2500
B     100
C    6400
D     900
E    2500
dtype: int64

------------------------------------------------------------------------

### Q5. Find mean, min, max of a Series.

> 💡 **Hint:** Use `.mean()`, `.min()`, `.max()`, `.sum()`, `.median()`, `.std()` directly on the Series.

In [28]:
print('mean: ',s2.mean())
print('min: ',s2.min())
print('max: ',s2.max())
print('sum: ',s2.sum())
print('median: ',s2.median())
print('std: ',s2.std())

mean:  44.0
min:  10
max:  80
sum:  220
median:  50.0
std:  26.076809620810597

------------------------------------------------------------------------

### Q6. Apply conditional filtering on a Series.

> 💡 **Hint:** Use a boolean mask: `s[s > 50]`. You can also chain conditions with `&` and `|`.

In [36]:
msk = (s2 > 10) | (s2 < 50)  
print('|(or): \n',s2[msk])

msk = (s2 > 10) & (s2 < 50)  
print('\n&(and): \n',s2[msk])

|(or):
 A    50
B    10
C    80
D    30
E    50
dtype: int64

&(and):
 D    30
dtype: int64

------------------------------------------------------------------------

### Q7. Replace values in a Series.

> 💡 **Hint:** Use `.replace(old_val, new_val)` or pass a dictionary `{old: new}` to replace multiple values at once.

In [41]:
s2.replace('A','a')

A    50
B    10
C    80
D    30
E    50
dtype: int64

In [ ]:
s2 = s2.replace(50,40)
print('replace single val: \n',s2)

s2 = s2.replace({10:20,80:70,30:40})
print('replace multiple val: \n',s2)

replace single val:
 A    40
B    10
C    80
D    30
E    40
dtype: int64
replace multiple val:
 A    40
B    20
C    70
D    40
E    40
dtype: int64

------------------------------------------------------------------------

### Q8. Convert Series data type.

> 💡 **Hint:** Use `.astype(dtype)` — e.g., `.astype(int)`, `.astype(float)`, `.astype("category")`.

In [47]:
print('change in float: \n',s2.astype(float))
print('change in category: \n',s2.astype('category'))

change in float:
 A    40.0
B    20.0
C    70.0
D    40.0
E    40.0
dtype: float64
change in category:
 A    40
B    20
C    70
D    40
E    40
dtype: category
Categories (3, int64): [20, 40, 70]

------------------------------------------------------------------------

### Q9. Check for null values in Series.

> 💡 **Hint:** Use `.isnull()` (returns boolean Series) or `.isnull().sum()` for a count.

In [52]:
print('check null values: \n',s2.isnull())
print('count: ',s2.isnull().sum())

check null values:
 A    False
B    False
C    False
D    False
E    False
dtype: bool
count:  0

------------------------------------------------------------------------

### Q10. Fill missing values in Series.

> 💡 **Hint:** Use `.fillna(value)` for constant, `.fillna(s.mean())` for mean, `.ffill()` for forward fill, `.bfill()` for backward fill.

In [70]:
import numpy as np

s10 = pd.Series([10,np.nan,30,np.nan,40,np.nan])
s10_v = s10.fillna(20)
print('fill by value: \n',s10_v)
s10_m = s10.fillna(s2.mean())
print(f'\nby mean: (mean:{s2.mean()})\n{s10_m}')
s10_f = s10.ffill()
print('\nby ffill(): \n',s10_f)
s10_b = s10.bfill()
print('\nby bfill(): \n',s10_b)

fill by value:
 0    10.0
1    20.0
2    30.0
3    20.0
4    40.0
5    20.0
dtype: float64

by mean: (mean:44.0)
0    10.0
1    44.0
2    30.0
3    44.0
4    40.0
5    44.0
dtype: float64

by ffill():
 0    10.0
1    10.0
2    30.0
3    30.0
4    40.0
5    40.0
dtype: float64

by bfill():
 0    10.0
1    30.0
2    30.0
3    40.0
4    40.0
5     NaN
dtype: float64

------------------------------------------------------------------------

### Q11. Create DataFrame from a list.

> 💡 **Hint:** Use `pd.DataFrame(list_of_lists, columns=[...])`. Each inner list becomes one row.

In [73]:
df11 = pd.DataFrame([[10,'Aman'],[20,'Rahul'],[30,'Raj'],[40,"Ram"],[50,'Ravi']], columns=['no','name'])
df11

   no   name
0  10   Aman
1  20  Rahul
2  30    Raj
3  40    Ram
4  50   Ravi

------------------------------------------------------------------------

### Q12. Create DataFrame from a dictionary.

> 💡 **Hint:** Use `pd.DataFrame({col: values})`. Keys become column names; values must have equal length.

In [74]:
df12 = pd.DataFrame({
    'no': [10, 20, 30, 40, 50],
    'name': ['Sayali', 'Rani', 'Sham', 'Jay', 'Sai']
})
print(df12)

   no    name
0  10  Sayali
1  20    Rani
2  30    Sham
3  40     Jay
4  50     Sai

------------------------------------------------------------------------

### Q13. Create DataFrame from list of dictionaries.

> 💡 **Hint:** Use `pd.DataFrame([{...}, {...}])`. Each dict is a row; missing keys become `NaN`.

In [105]:
row_list = [
    {'Roll_No': 10, 'Name': 'Aman', 'Marks': 85},
    {'Roll_No': 20, 'Name': 'Rahul'},               # Missing 'Marks'
    {'Roll_No': 30, 'Name': 'Raj', 'Marks': 78, 'Grade': 'B'} # Extra 'Grade'
]
df13 = pd.DataFrame(row_list)
print(df13)

   Roll_No   Name  Marks Grade
0       10   Aman   85.0   NaN
1       20  Rahul    NaN   NaN
2       30    Raj   78.0     B

------------------------------------------------------------------------

### Q14. Display DataFrame structure (shape, columns, dtypes).

> 💡 **Hint:** Use `df.shape`, `df.columns`, `df.dtypes`, `df.info()`, and `df.describe()`.

In [106]:
df14 = pd.DataFrame({
    'no': [10, 20, 30, 40, 50],
    'name': ['Sayali', 'Rani', 'Sham', 'Jay', 'Sai']
})
print('shape: ',df14.shape)
print('\ncolumns: \n',df14.columns)
print('\ndtype: \n',df14.dtypes)

shape:  (5, 2)

columns:
 Index(['no', 'name'], dtype='str')

dtype:
 no      int64
name      str
dtype: object

------------------------------------------------------------------------

### Q15. Select single column from DataFrame.

> 💡 **Hint:** Use `df["col_name"]` — this returns a **Series**. You can also use `df.col_name` (dot notation).

In [107]:
print(df13)
print('\nsingle col: \n',df13['Name'])
print('\nusing dot notation: \n',df13.Name)

   Roll_No   Name  Marks Grade
0       10   Aman   85.0   NaN
1       20  Rahul    NaN   NaN
2       30    Raj   78.0     B

single col:
 0     Aman
1    Rahul
2      Raj
Name: Name, dtype: str

using dot notation:
 0     Aman
1    Rahul
2      Raj
Name: Name, dtype: str

------------------------------------------------------------------------

### Q16. Select multiple columns.

> 💡 **Hint:** Use `df[["col1", "col2"]]` with a list inside the brackets — this returns a **DataFrame**.

In [108]:
print(df13)
print('\nmultiple col: \n',df13[['Marks','Grade']])

   Roll_No   Name  Marks Grade
0       10   Aman   85.0   NaN
1       20  Rahul    NaN   NaN
2       30    Raj   78.0     B

multiple col:
    Marks Grade
0   85.0   NaN
1    NaN   NaN
2   78.0     B

------------------------------------------------------------------------

### Q17. Add new column with scalar value.

> 💡 **Hint:** `df["new_col"] = 10` — the scalar is **broadcast** to all rows automatically.

In [109]:
print(df13)
df13['Age'] = 20
print('\nadd col: \n',df13)

   Roll_No   Name  Marks Grade
0       10   Aman   85.0   NaN
1       20  Rahul    NaN   NaN
2       30    Raj   78.0     B

add col:
    Roll_No   Name  Marks Grade  Age
0       10   Aman   85.0   NaN   20
1       20  Rahul    NaN   NaN   20
2       30    Raj   78.0     B   20

------------------------------------------------------------------------

### Q18. Add column using Series.

> 💡 **Hint:** `df["new_col"] = pd.Series([...])`. The Series index must align with the DataFrame index.

In [110]:
print(df13)
df13['City'] = pd.Series(['Pune','Mumbai','Nagpur'])
print('\nadd col using series: \n',df13)

   Roll_No   Name  Marks Grade  Age
0       10   Aman   85.0   NaN   20
1       20  Rahul    NaN   NaN   20
2       30    Raj   78.0     B   20

add col using series:
    Roll_No   Name  Marks Grade  Age    City
0       10   Aman   85.0   NaN   20    Pune
1       20  Rahul    NaN   NaN   20  Mumbai
2       30    Raj   78.0     B   20  Nagpur

------------------------------------------------------------------------

### Q19. Rename columns using `rename()`.

> 💡 **Hint:** Use `df.rename(columns={"old": "new"})`. Add `inplace=True` to modify in-place.

In [111]:
df13.rename(columns={'Roll_No':'rno'}, inplace=True)
print('rename single col: \n',df13)

rename single col:
    rno   Name  Marks Grade  Age    City
0   10   Aman   85.0   NaN   20    Pune
1   20  Rahul    NaN   NaN   20  Mumbai
2   30    Raj   78.0     B   20  Nagpur

------------------------------------------------------------------------

### Q20. Rename multiple columns.

> 💡 **Hint:** Pass a dictionary with multiple key-value pairs to `rename(columns={...})`.

In [ ]:
df13.rename(columns={'Name':'name','Marks':'marks'}, inplace=True)
print('rename single col: \n',df13)

rename single col:
    rno   name  marks Grade  Age    City
0   10   Aman   85.0   NaN   20    Pune
1   20  Rahul    NaN   NaN   20  Mumbai
2   30    Raj   78.0     B   20  Nagpur

------------------------------------------------------------------------

## 🔹 Section 2: Indexing, Selection & Slicing (Q21–Q40)

------------------------------------------------------------------------

### Q21. Select rows using `loc`.

> 💡 **Hint:** `df.loc[label]` for a single row, `df.loc[label1:label2]` for a range. **Inclusive on both ends.**

In [209]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age':[20,30,40,50,30],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney'],
    'Salary': [70000, 85000, 95000, 120000, 110000]
}
df21 = pd.DataFrame(data, index=['r1', 'r2', 'r3', 'r4', 'r5'])

print(df21)
print('\nsingle row: \n',df21.loc['r2'])
print('\nmultiple row: \n',df21.loc['r2':'r5'])

       Name  Age      City  Salary
r1    Alice   20  New York   70000
r2      Bob   30    London   85000
r3  Charlie   40     Paris   95000
r4    David   50     Tokyo  120000
r5      Eva   30    Sydney  110000

single row:
 Name         Bob
Age           30
City      London
Salary     85000
Name: r2, dtype: object

multiple row:
        Name  Age    City  Salary
r2      Bob   30  London   85000
r3  Charlie   40   Paris   95000
r4    David   50   Tokyo  120000
r5      Eva   30  Sydney  110000


------------------------------------------------------------------------

### Q22. Select rows using `iloc`.

> 💡 **Hint:** `df.iloc[0]` for first row, `df.iloc[1:4]` for rows 1–3. **Exclusive on the end** (Python-style).

In [197]:
print(df21)
print('\nsingle row: \n',df21.iloc[0])
print('\n1-3 row: \n',df21.iloc[1:4])

       Name  Age      City  Salary
r1    Alice   20  New York   70000
r2      Bob   30    London   85000
r3  Charlie   40     Paris   95000
r4    David   50     Tokyo  120000
r5      Eva   30    Sydney  110000

single row:
 Name         Alice
Age             20
City      New York
Salary       70000
Name: r1, dtype: object

1-3 row:
        Name  Age    City  Salary
r2      Bob   30  London   85000
r3  Charlie   40   Paris   95000
r4    David   50   Tokyo  120000

------------------------------------------------------------------------

### Q23. Access specific row and column.

> 💡 **Hint:** `df.loc[row_label, "col_name"]` or `df.iloc[row_pos, col_pos]` for a single cell.

In [198]:
print(df21)
print('\nsingle cell using loc: \n',df21.loc['r2','City'])
print('\nusing iloc: \n',df21.iloc[1,1])

       Name  Age      City  Salary
r1    Alice   20  New York   70000
r2      Bob   30    London   85000
r3  Charlie   40     Paris   95000
r4    David   50     Tokyo  120000
r5      Eva   30    Sydney  110000

single cell using loc:
 London

using iloc:
 30

------------------------------------------------------------------------

### Q24. Select subset using multiple rows & columns.

> 💡 **Hint:** `df.loc[[r1,r2], ["col1","col2"]]` or `df.iloc[[0,1], [0,2]]`.

In [199]:
print(df21)
print('\nmultiple row & cols using loc: \n',df21.loc[['r1','r2'], ["Name","Salary"]])
print('\nusing iloc : \n',df21.iloc[[0,1],[0,2]])

       Name  Age      City  Salary
r1    Alice   20  New York   70000
r2      Bob   30    London   85000
r3  Charlie   40     Paris   95000
r4    David   50     Tokyo  120000
r5      Eva   30    Sydney  110000

multiple row & cols using loc:
      Name  Salary
r1  Alice   70000
r2    Bob   85000

using iloc :
      Name      City
r1  Alice  New York
r2    Bob    London

------------------------------------------------------------------------

### Q25. Apply conditional filtering using `loc`.

> 💡 **Hint:** `df.loc[df["col"] > value, ["col1","col2"]]` — pass a boolean Series as the row selector.

In [200]:
print(df21)
new = df21.loc[df21['Salary'] > 90000,['Name','City','Salary']]
print('\napply condition using loc : \n',new)

       Name  Age      City  Salary
r1    Alice   20  New York   70000
r2      Bob   30    London   85000
r3  Charlie   40     Paris   95000
r4    David   50     Tokyo  120000
r5      Eva   30    Sydney  110000

apply condition using loc :
        Name    City  Salary
r3  Charlie   Paris   95000
r4    David   Tokyo  120000
r5      Eva  Sydney  110000

------------------------------------------------------------------------

### Q26. Slice rows using index range.

> 💡 **Hint:** Use `df.iloc[start:end]` for position-based slicing or `df.loc[label1:label2]` for label-based slicing.

In [201]:
print(df21)
print('\nposition-based slicing: \n',df21.iloc[1:4])
print('\nlabel-based slicing: \n',df21.loc['r2':'r4'])

       Name  Age      City  Salary
r1    Alice   20  New York   70000
r2      Bob   30    London   85000
r3  Charlie   40     Paris   95000
r4    David   50     Tokyo  120000
r5      Eva   30    Sydney  110000

position-based slicing:
        Name  Age    City  Salary
r2      Bob   30  London   85000
r3  Charlie   40   Paris   95000
r4    David   50   Tokyo  120000

label-based slicing:
        Name  Age    City  Salary
r2      Bob   30  London   85000
r3  Charlie   40   Paris   95000
r4    David   50   Tokyo  120000

------------------------------------------------------------------------

### Q27. Slice columns using labels.

> 💡 **Hint:** `df.loc[:, "col1":"col3"]` — selects all rows, columns from col1 to col3 (label-inclusive).

In [202]:
print(df21)
print('\nselect all rows using loc: \n',df21.loc[:,'Name':'Salary'])

       Name  Age      City  Salary
r1    Alice   20  New York   70000
r2      Bob   30    London   85000
r3  Charlie   40     Paris   95000
r4    David   50     Tokyo  120000
r5      Eva   30    Sydney  110000

select all rows using loc:
        Name  Age      City  Salary
r1    Alice   20  New York   70000
r2      Bob   30    London   85000
r3  Charlie   40     Paris   95000
r4    David   50     Tokyo  120000
r5      Eva   30    Sydney  110000

------------------------------------------------------------------------

### Q28. Slice columns using position.

> 💡 **Hint:** `df.iloc[:, 1:4]` — selects all rows, columns at positions 1, 2, 3.

In [203]:
print(df21)
print('\nselect alll rows using iloc: \n',df21.iloc[:,1:4])

       Name  Age      City  Salary
r1    Alice   20  New York   70000
r2      Bob   30    London   85000
r3  Charlie   40     Paris   95000
r4    David   50     Tokyo  120000
r5      Eva   30    Sydney  110000

select alll rows using iloc:
     Age      City  Salary
r1   20  New York   70000
r2   30    London   85000
r3   40     Paris   95000
r4   50     Tokyo  120000
r5   30    Sydney  110000

------------------------------------------------------------------------

### Q29. Perform combined row & column slicing.

> 💡 **Hint:** `df.loc[row_condition, ["col1","col2"]]` or `df.iloc[0:5, [0, 2, 4]]`.

In [204]:
print(df21)
print('\ncombine rows & col using loc: \n',df21.loc['r1':'r5',['Name','City']])
print('\ncombine rows & col using iloc: \n',df21.iloc[0:5,[0,2]])

       Name  Age      City  Salary
r1    Alice   20  New York   70000
r2      Bob   30    London   85000
r3  Charlie   40     Paris   95000
r4    David   50     Tokyo  120000
r5      Eva   30    Sydney  110000

combine rows & col using loc:
        Name      City
r1    Alice  New York
r2      Bob    London
r3  Charlie     Paris
r4    David     Tokyo
r5      Eva    Sydney

combine rows & col using iloc:
        Name      City
r1    Alice  New York
r2      Bob    London
r3  Charlie     Paris
r4    David     Tokyo
r5      Eva    Sydney

------------------------------------------------------------------------

### Q30. Set a column as index.

> 💡 **Hint:** Use `df.set_index("col_name")`. Add `inplace=True` to modify without reassigning.

In [232]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age':[20,30,40,50,30],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney'],
    'Salary': [70000, 85000, 95000, 120000, 110000]
}
df30 = pd.DataFrame(data, index=['r1', 'r2', 'r3', 'r4', 'r5'])

In [233]:
print(df30)
df30.set_index('Name',inplace=True)
print('\nset col as idx: \n',df30)

       Name  Age      City  Salary
r1    Alice   20  New York   70000
r2      Bob   30    London   85000
r3  Charlie   40     Paris   95000
r4    David   50     Tokyo  120000
r5      Eva   30    Sydney  110000

set col as idx:
          Age      City  Salary
Name
Alice     20  New York   70000
Bob       30    London   85000
Charlie   40     Paris   95000
David     50     Tokyo  120000
Eva       30    Sydney  110000

------------------------------------------------------------------------

### Q31. Create hierarchical index (MultiIndex).

> 💡 **Hint:** `df.set_index(["col1","col2"])` — pass a **list** of column names to create a MultiIndex.

In [234]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva'],
    'Age':[20,30,40,50,30],
    'City': ['New York', 'London', 'Paris', 'Tokyo', 'Sydney'],
    'Salary': [70000, 85000, 95000, 120000, 110000]
}
df31 = pd.DataFrame(data, index=['r1', 'r2', 'r3', 'r4', 'r5'])

In [235]:
df31 = df31.set_index(['Name','City'])
print('\nset col as idx: \n',df31)

set col as idx:
                   Age  Salary
Name    City
Alice   New York   20   70000
Bob     London     30   85000
Charlie Paris      40   95000
David   Tokyo      50  120000
Eva     Sydney     30  110000

------------------------------------------------------------------------

### Q32. Reset index.

> 💡 **Hint:** `df.reset_index()` — moves the current index back to a column. Use `inplace=True` to modify in-place.

In [236]:
print('with index: \n',df30)
df30.reset_index(inplace=True)
print('\nreset index on col : \n',df30)

with index:
          Age      City  Salary
Name
Alice     20  New York   70000
Bob       30    London   85000
Charlie   40     Paris   95000
David     50     Tokyo  120000
Eva       30    Sydney  110000

reset index on col :
       Name  Age      City  Salary
0    Alice   20  New York   70000
1      Bob   30    London   85000
2  Charlie   40     Paris   95000
3    David   50     Tokyo  120000
4      Eva   30    Sydney  110000

------------------------------------------------------------------------

### Q33. Reset multi-index.

> 💡 **Hint:** `df.reset_index()` on a MultiIndex DataFrame flattens both index levels back to columns.

In [237]:
print('with multiindex: \n',df31)
df31.reset_index(inplace=True)
print('\nreset index on col : \n',df31)

with multiindex:
                   Age  Salary
Name    City
Alice   New York   20   70000
Bob     London     30   85000
Charlie Paris      40   95000
David   Tokyo      50  120000
Eva     Sydney     30  110000

reset index on col :
       Name      City  Age  Salary
0    Alice  New York   20   70000
1      Bob    London   30   85000
2  Charlie     Paris   40   95000
3    David     Tokyo   50  120000
4      Eva    Sydney   30  110000

------------------------------------------------------------------------

### Q34. Convert index to column.

> 💡 **Hint:** `df.reset_index()` by default moves the index to a column. Use `drop=False` (default) to keep it.

In [245]:
data = {'Age':20, 'Salary':20000}
df = pd.DataFrame(data, index=['r1', 'r2'])
print('original: \n',df)

df.reset_index(drop=False, inplace=True)
print('\nafter reset: \n',df)

original:
     Age  Salary
r1   20   20000
r2   20   20000

after reset:
   index  Age  Salary
0    r1   20   20000
1    r2   20   20000

------------------------------------------------------------------------

### Q35. Use drop option in `reset_index`.

> 💡 **Hint:** `df.reset_index(drop=True)` discards the old index completely instead of converting it to a column.

In [246]:
data = {'Age':20, 'Salary':20000}
df = pd.DataFrame(data, index=['r1', 'r2'])
print('original: \n',df)

df.reset_index(drop=True, inplace=True)
print('\nafter reset: \n',df)

original:
     Age  Salary
r1   20   20000
r2   20   20000

after reset:
    Age  Salary
0   20   20000
1   20   20000

------------------------------------------------------------------------

### Q36. Perform label-based indexing.

> 💡 **Hint:** Use `df.loc[label]` — works with any index type (string, integer, datetime labels).

In [291]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David'],
    'Age': [25, 30, 35, 40],
    'City': ['Pune', 'Mumbai', 'Delhi', 'Bangalore']
}
df36 = pd.DataFrame(data, index=['a', 'b', 'c', 'd'])

print("Original DataFrame:\n", df36, "\n")
print("Row with label 'b':\n", df36.loc['b'])

Original DataFrame:
       Name  Age       City
a    Alice   25       Pune
b      Bob   30     Mumbai
c  Charlie   35      Delhi
d    David   40  Bangalore

Row with label 'b':
 Name       Bob
Age         30
City    Mumbai
Name: b, dtype: object

------------------------------------------------------------------------

### Q37. Perform position-based indexing.

> 💡 **Hint:** Use `df.iloc[0]` — always integer-based, regardless of the index type.

In [292]:
print("Original DataFrame:\n", df36, "\n")
print("Row with index 0:\n", df36.iloc[0])

Original DataFrame:
       Name  Age       City
a    Alice   25       Pune
b      Bob   30     Mumbai
c  Charlie   35      Delhi
d    David   40  Bangalore

Row with index 0:
 Name    Alice
Age        25
City     Pune
Name: a, dtype: object

------------------------------------------------------------------------

### Q38. Access first N rows.

> 💡 **Hint:** `df.head(N)` — default N is 5.

In [247]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Albert','kim seon-ho'],
    'Age':[20,30,40,50,30,34,45]
    }
df38 = pd.DataFrame(data)
df38.head()

      Name  Age
0    Alice   20
1      Bob   30
2  Charlie   40
3    David   50
4      Eva   30

------------------------------------------------------------------------

### Q39. Access last N rows.

> 💡 **Hint:** `df.tail(N)` — default N is 5.

In [248]:
df38.tail()

          Name  Age
2      Charlie   40
3        David   50
4          Eva   30
5       Albert   34
6  kim seon-ho   45

------------------------------------------------------------------------

### Q40. Extract random sample from DataFrame.

> 💡 **Hint:** `df.sample(n=5)` for random rows, `df.sample(frac=0.2)` for 20% of rows. Set `random_state` for reproducibility.

In [256]:
print('random row: \n',df38.sample(n=5))
print('\n20% of row: \n',df38.sample(frac=0.2,random_state=42))

random row:
           Name  Age
2      Charlie   40
3        David   50
0        Alice   20
6  kim seon-ho   45
4          Eva   30

20% of row:
     Name  Age
0  Alice   20

------------------------------------------------------------------------

## 🔹 Section 3: Data Cleaning (Q41–Q60)

------------------------------------------------------------------------

### Q41. Detect missing values using `isnull()`.

> 💡 **Hint:** `df.isnull()` returns a boolean DataFrame. Use `.isnull().sum()` for column-wise counts or `.isnull().any()` to check if any exist.

In [261]:
data = {
    'Name': ['Alice', 'Bob', 'Charlie', 'David', 'Eva', 'Albert','kim seon-ho'],
    'Age':[20,np.nan,40,np.nan,30,np.nan,45]
    }
df41 = pd.DataFrame(data)

print('.isnull().sum(): \n',df41.isnull().sum())
print('\n.isnull().any(): \n',df41.isnull().any())

.isnull().sum():
 Name    0
Age     3
dtype: int64

.isnull().any():
 Name    False
Age      True
dtype: bool

------------------------------------------------------------------------

### Q42. Drop missing values using `dropna()`.

> 💡 **Hint:** `df.dropna()` drops any row with a NaN. Use `axis=1` for columns, `subset=["col"]` for specific columns, and `thresh=N` to keep rows with at least N non-null values.

In [262]:
data = {
    "A": [1, 2, np.nan, 4],
    "B": [5, np.nan, np.nan, 8],
    "C": [9, 10, 11, 12]
}
df = pd.DataFrame(data)

print("Original DataFrame:")
print(df)

df_drop_rows = df.dropna()
print("\nDrop rows with any NaN values:")
print(df_drop_rows)

df_drop_cols = df.dropna(axis=1)
print("\nDrop columns with any NaN values:")
print(df_drop_cols)

df_drop_subset = df.dropna(subset=["B"])
print("\nDrop rows where column 'B' has NaN:")
print(df_drop_subset)

df_thresh = df.dropna(thresh=2)
print("\nKeep rows with at least 2 non-null values:")
print(df_thresh)

Original DataFrame:
     A    B   C
0  1.0  5.0   9
1  2.0  NaN  10
2  NaN  NaN  11
3  4.0  8.0  12

Drop rows with any NaN values:
     A    B   C
0  1.0  5.0   9
3  4.0  8.0  12

Drop columns with any NaN values:
    C
0   9
1  10
2  11
3  12

Drop rows where column 'B' has NaN:
     A    B   C
0  1.0  5.0   9
3  4.0  8.0  12

Keep rows with at least 2 non-null values:
     A    B   C
0  1.0  5.0   9
1  2.0  NaN  10
3  4.0  8.0  12

------------------------------------------------------------------------

### Q43. Fill missing values with a constant.

> 💡 **Hint:** `df.fillna(0)` or `df["col"].fillna("Unknown")`. You can also pass a dict to fill different columns with different values.

In [267]:
print("Original DataFrame:")
print(df)
fill_unknown = df['A'].fillna('unknown')
print('\nfill with constant value: ')
print(fill_unknown)

Original DataFrame:
     A    B   C
0  1.0  5.0   9
1  2.0  NaN  10
2  NaN  NaN  11
3  4.0  8.0  12

fill with constant value:
0        1.0
1        2.0
2    unknown
3        4.0
Name: A, dtype: object

------------------------------------------------------------------------

### Q44. Fill missing values using mean/median.

> 💡 **Hint:** `df["col"].fillna(df["col"].mean())` or `df["col"].fillna(df["col"].median())`.

In [277]:
print("Original DataFrame:")
print(df[['A','B']])

fill_mean = df['A'].fillna(df['A'].mean())
print('\nfill with mean value: ')
print(fill_mean)

fill_median = df['B'].fillna(df['B'].median())
print('\nfill with median value: ')
print(fill_median)

Original DataFrame:
     A    B
0  1.0  5.0
1  2.0  NaN
2  NaN  NaN
3  4.0  8.0

fill with mean value:
0    1.000000
1    2.000000
2    2.333333
3    4.000000
Name: A, dtype: float64

fill with median value:
0    5.0
1    6.5
2    6.5
3    8.0
Name: B, dtype: float64

------------------------------------------------------------------------

### Q45. Use forward fill and backward fill.

> 💡 **Hint:** `df.ffill()` propagates the last valid value forward. `df.bfill()` fills using the next valid value.

In [276]:
print("Original DataFrame:")
print(df['A'])

fill_ffill = df['A'].ffill()
print('\nfill with ffill value: ')
print(fill_ffill)

fill_bfill = df['A'].bfill()
print('\nfill with bfill value: ')
print(fill_bfill)

Original DataFrame:
0    1.0
1    2.0
2    NaN
3    4.0
Name: A, dtype: float64

fill with ffill value:
0    1.0
1    2.0
2    2.0
3    4.0
Name: A, dtype: float64

fill with bfill value:
0    1.0
1    2.0
2    4.0
3    4.0
Name: A, dtype: float64

------------------------------------------------------------------------

### Q46. Convert data type using `astype()`.

> 💡 **Hint:** `df["col"].astype(int)` or `df["col"].astype("category")`. Use `errors="coerce"` inside `pd.to_numeric()` to handle invalid values.

In [3]:
data = {
    "id": ["1", "2", "3", "4"],
    "age": ["25", "30", "invalid", "40"],
    "gender": ["M", "F", "M", "F"]
}
df46 = pd.DataFrame(data)

print("Original DataFrame:")
print(df46)
print("\nData types:")
print(df46.dtypes)

df46["id"] = df46["id"].astype(int)
df46["gender"] = df46["gender"].astype("category")
df46["age"] = pd.to_numeric(df46["age"], errors="coerce")

print("\nDataFrame after conversions:")
print(df46)
print("\nData types after conversion:")
print(df46.dtypes)

Original DataFrame:
  id      age gender
0  1       25      M
1  2       30      F
2  3  invalid      M
3  4       40      F

Data types:
id        str
age       str
gender    str
dtype: object

DataFrame after conversions:
   id   age gender
0   1  25.0      M
1   2  30.0      F
2   3   NaN      M
3   4  40.0      F

Data types after conversion:
id           int64
age        float64
gender    category
dtype: object

------------------------------------------------------------------------

### Q47. Clean string column using `.str.lower()`.

> 💡 **Hint:** Access the `.str` accessor first: `df["col"].str.lower()`. Similarly `.str.upper()`, `.str.title()`.

In [3]:
data = {
    "id": [1, 2, 3, 4],
    "name": ["Ganesh", "Mahesh", "Raj", "Jay"],
}
df47 = pd.DataFrame(data)

print("Original col:")
print(df47['name'])

print("\nafter lower:")
print(df47['name'].str.lower())

print("\nafter upper:")
print(df47['name'].str.upper())

print("\nafter title:")
print(df47['name'].str.title())

Original col:
0    Ganesh
1    Mahesh
2       Raj
3       Jay
Name: name, dtype: str

after lower:
0    ganesh
1    mahesh
2       raj
3       jay
Name: name, dtype: str

after upper:
0    GANESH
1    MAHESH
2       RAJ
3       JAY
Name: name, dtype: str

after title:
0    Ganesh
1    Mahesh
2       Raj
3       Jay
Name: name, dtype: str

------------------------------------------------------------------------

### Q48. Trim whitespace in strings.

> 💡 **Hint:** `df["col"].str.strip()` removes leading and trailing spaces. Use `.str.lstrip()` / `.str.rstrip()` for one side.

In [7]:
data = {
    "id": [1, 2, 3, 4],
    "name": [" Ganesh ", " Mahesh ", " Raj", "Jay "],
}
df48 = pd.DataFrame(data)

print("Original col:")
print(df48['name'])

print('\nafter removes leading and trailing space:')
print(df48['name'].str.strip())

print('\nafter removes leading space:')
print(df48['name'].str.lstrip())

print('\nafter removes trailing space:')
print(df48['name'].str.rstrip())

Original col:
0     Ganesh
1     Mahesh
2         Raj
3        Jay
Name: name, dtype: str

after removes leading and trailing space:
0    Ganesh
1    Mahesh
2       Raj
3       Jay
Name: name, dtype: str

after removes leading space:
0    Ganesh
1    Mahesh
2        Raj
3       Jay
Name: name, dtype: str

after removes trailing space:
0     Ganesh
1     Mahesh
2        Raj
3        Jay
Name: name, dtype: str

------------------------------------------------------------------------

### Q49. Replace substring in column.

> 💡 **Hint:** `df["col"].str.replace("old", "new")`. Add `regex=True` for pattern-based replacement.

In [14]:
data = {
    "id": [1, 2, 3, 4],
    "name": ["Ganesh12", "Mahesh12", "Raj12", "Jay12"],
}
df49 = pd.DataFrame(data)

print("Original col: ")
print(df49['name'])

print('\nreplace substring: ')
print(df49['name'].str.replace('Mahesh12','Rajesh'))

print('\npattern based replacement: ')
print(df49['name'].str.replace(r'\d+','', regex=True))

Original col:
0    Ganesh12
1    Mahesh12
2       Raj12
3       Jay12
Name: name, dtype: str

replace substring:
0    Ganesh12
1      Rajesh
2       Raj12
3       Jay12
Name: name, dtype: str

pattern based replacement:
0    Ganesh
1    Mahesh
2       Raj
3       Jay
Name: name, dtype: str

------------------------------------------------------------------------

### Q50. Extract part of string using `.str`.

> 💡 **Hint:** `df["col"].str[:3]` for first 3 chars. Use `.str.split("@").str[1]` to extract after a delimiter.

In [20]:
data = {
    "id": [1, 2, 3, 4],
    "name": ["Ganesh@gmail", "Mahesh@yahoo", "Raj@bing", "Jay@outlook"],
}
df50 = pd.DataFrame(data)

print("Original col: ")
print(df50['name'])

print('\nfirst 3 chars:')
print(df50['name'].str[:3])

print('\nextract after delimiter:')
print(df50['name'].str.split('@').str[1])

Original col:
0    Ganesh@gmail
1    Mahesh@yahoo
2        Raj@bing
3     Jay@outlook
Name: name, dtype: str

first 3 chars:
0    Gan
1    Mah
2    Raj
3    Jay
Name: name, dtype: str

extract after delimiter:
0      gmail
1      yahoo
2       bing
3    outlook
Name: name, dtype: object

------------------------------------------------------------------------

### Q51. Detect duplicate rows.

> 💡 **Hint:** `df.duplicated()` returns a boolean Series. Use `df[df.duplicated()]` to see the actual duplicate rows.

In [30]:
data = {
    "id": [1, 2, 3, 4],
    "name": ["Jay", "Mahesh", "Raj", "Jay"],
}
df51 = pd.DataFrame(data)

print("Original col: ")
print(df51['name'])

print('\nboolean series: ')
print(df51.duplicated(subset=['name']))

print('\nactual duplicates rows: ')
df51[df51.duplicated(subset=['name'],keep=False)]

Original col:
0       Jay
1    Mahesh
2       Raj
3       Jay
Name: name, dtype: str

boolean series:
0    False
1    False
2    False
3     True
dtype: bool

actual duplicates rows:

   id name
0   1  Jay
3   4  Jay

------------------------------------------------------------------------

### Q52. Remove duplicates using `drop_duplicates()`.

> 💡 **Hint:** `df.drop_duplicates()` keeps the first occurrence by default. Use `subset=["col"]` to check specific columns, and `keep="last"` or `keep=False`.

In [38]:
print("Original col: ")
print(df51['name'])

print('\ndrop duplicates based on cols:')
print(df51.drop_duplicates(subset=["name"]))

print('\nKeep the Last Occurrence:')
print(df51.drop_duplicates(subset=["name"], keep="last"))

print('\nremove all occurences of duplicates')
print(df51.drop_duplicates(subset=["name"], keep=False))

Original col:
0       Jay
1    Mahesh
2       Raj
3       Jay
Name: name, dtype: str

drop duplicates based on cols:
   id    name
0   1     Jay
1   2  Mahesh
2   3     Raj

Keep the Last Occurrence:
   id    name
1   2  Mahesh
2   3     Raj
3   4     Jay

remove all occurences of duplicates
   id    name
1   2  Mahesh
2   3     Raj

------------------------------------------------------------------------

### Q53. Rename row labels.

> 💡 **Hint:** `df.rename(index={old_label: new_label})`.

In [40]:
print("Original data: ")
print(df51)

df_renamed = df51.rename(index={0: "Row_A", 1: "Row_B"})
print('\nrename row labels: ')
print(df_renamed)

Original data:
   id    name
0   1     Jay
1   2  Mahesh
2   3     Raj
3   4     Jay

rename row labels:
       id    name
Row_A   1     Jay
Row_B   2  Mahesh
2       3     Raj
3       4     Jay

------------------------------------------------------------------------

### Q54. Handle inconsistent data.

> 💡 **Hint:** Use `.str.strip().str.lower()` to normalize strings. Use `.replace({...})` to map inconsistent values to a standard form.

In [49]:
bad_data = {
    "id": [1,2,3,4],
    "name": [" Jay ", "Msh", "Raj", "JAY"]
}
df54 = pd.DataFrame(bad_data)
print('original col')
print(df54['name'])

print('\nStrip spaces and convert lower:')
print(df54["name"].str.strip().str.lower())

print('\nStandardise form: ')
print(df54["name"].replace({"Msh": "Mahesh"}))

original col
0     Jay
1      Msh
2      Raj
3      JAY
Name: name, dtype: str

Strip spaces and convert lower:
0    jay
1    msh
2    raj
3    jay
Name: name, dtype: str

Standardise form:
0      Jay
1    Mahesh
2       Raj
3       JAY
Name: name, dtype: str

------------------------------------------------------------------------

### Q55. Replace values in DataFrame.

> 💡 **Hint:** `df.replace("old", "new")` works DataFrame-wide. Pass a dict `{old: new}` or nested dict `{"col": {old: new}}` for column-specific replacement.

In [54]:
print('original col:')
print(df54['name'])

print('\ncol specific replacement: ')
print(df54.replace("Msh", "Mahesh"))

print('\nnested dict: ')
print(df51.replace({"name": {"Jay": "Jason"}}))

original col:
0     Jay
1      Msh
2      Raj
3      JAY
Name: name, dtype: str

col specific replacement:
   id    name
0   1    Jay
1   2  Mahesh
2   3     Raj
3   4     JAY

nested dict:
   id    name
0   1   Jason
1   2  Mahesh
2   3     Raj
3   4   Jason

------------------------------------------------------------------------

### Q56. Detect outliers in a column.

> 💡 **Hint:** Use the **IQR method**: compute Q1, Q3, IQR = Q3–Q1. Outliers are values below `Q1 - 1.5*IQR` or above `Q3 + 1.5*IQR`. Alternatively use Z-score: `|z| > 3`.

In [7]:
data = {
    'value': [10, 12, 14, 15, 18, 20, 22, 100]
    }
df56 = pd.DataFrame(data)

Q1 = df['value'].quantile(0.25)
Q3 = df['value'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df[(df['value'] < lower_bound) | (df['value'] > upper_bound)]

print("Outliers:")
print(outliers)

Outliers:
   value
7    100

------------------------------------------------------------------------

### Q57. Handle outliers using clipping.

> 💡 **Hint:** `df["col"].clip(lower=lo, upper=hi)` replaces values outside the bounds with the boundary values.

In [12]:
data = {
    'value': [10, 12, 14, 15, 18, 20, 22, 100]
    }
df56 = pd.DataFrame(data)

Q1 = df56['value'].quantile(0.25)
Q3 = df56['value'].quantile(0.75)
IQR = Q3 - Q1

lower_bound = Q1 - 1.5 * IQR
upper_bound = Q3 + 1.5 * IQR

outliers = df56[(df56['value'] < lower_bound) | (df56['value'] > upper_bound)]

print("Outliers:")
print(outliers)

df56['value_clipped'] = df56['value'].clip(lower=lower_bound,upper=upper_bound)
print('\nvalue after clipped: ')
print(df56)

Outliers:
   value
7    100

value after clipped:
   value  value_clipped
0     10             10
1     12             12
2     14             14
3     15             15
4     18             18
5     20             20
6     22             22
7    100             31

------------------------------------------------------------------------

### Q58. Standardize column names.

> 💡 **Hint:** `df.columns = df.columns.str.strip().str.lower().str.replace(" ", "_")` — clean all column names in one line.

In [ ]:
df = pd.DataFrame({
    ' First Name ': ['Alice', 'Bob'],
    'Age ': [25, 30],
    'City Name': ['New York', 'London']
})

print("Before:")
print(df.columns)

df.columns = (df.columns.str.strip().str.lower().str.replace(" ", "_"))

print("\nAfter:")
print(df.columns)

Before:
Index([' First Name ', 'Age ', 'City Name'], dtype='str')

After:
Index(['first_name', 'age', 'city_name'], dtype='str')

------------------------------------------------------------------------

### Q59. Handle mixed data types in a column.

> ***💡 **Hint:** Use `pd.to_numeric(df["col"], errors="coerce")` to convert to numbers, turning invalid strings into `NaN`.

In [16]:
df = pd.DataFrame({
    'value': ['10', '20', 'abc', '30', '40.5', 'N/A']
})

df['value'] = pd.to_numeric(df['value'], errors='coerce')

print(df)

   value
0   10.0
1   20.0
2    NaN
3   30.0
4   40.5
5    NaN

------------------------------------------------------------------------

### Q60. Remove special characters from text data.

> 💡 **Hint:** `df["col"].str.replace(r"[^a-zA-Z0-9 ]", "", regex=True)` — use regex to keep only alphanumeric characters.

In [17]:
df = pd.DataFrame({
    "text": ["Hello@World!", "Python#3.12", "Data$Science%", "A&B_C"]
})

df["clean_text"] = df["text"].str.replace(r"[^a-zA-Z0-9 ]", "", regex=True)

print(df)

            text   clean_text
0   Hello@World!   HelloWorld
1    Python#3.12    Python312
2  Data$Science%  DataScience
3          A&B_C          ABC

------------------------------------------------------------------------

## 🔹 Section 4: Data Manipulation (Q61–Q80)

------------------------------------------------------------------------

### Q61. Filter rows using AND condition.

> 💡 **Hint:** `df[(df["col1"] > val) & (df["col2"] == "x")]` — wrap each condition in parentheses and use `&`.

In [21]:
data = {
    'id': [1,2,3,4,5,6,7,8],
    'value': [10, 12, 14, 15, 18, 20, 22, 100]
    }
df56 = pd.DataFrame(data)

df56[(df56['id'] > 5) & (df56['value'] == 20)]

   id  value
5   6     20

------------------------------------------------------------------------

### Q62. Filter rows using OR condition.

> 💡 **Hint:** `df[(df["col1"] > val) | (df["col2"] == "x")]` — use `|` between conditions.

In [24]:
print('original data: ')
print(df56)

df56[(df56["id"] > 5) | (df56["value"] == 15)]

original data:
   id  value
0   1     10
1   2     12
2   3     14
3   4     15
4   5     18
5   6     20
6   7     22
7   8    100

   id  value
3   4     15
5   6     20
6   7     22
7   8    100

------------------------------------------------------------------------

### Q63. Filter rows using NOT condition.

> 💡 **Hint:** `df[~(df["col"] == "val")]` — use `~` to negate a boolean condition.

In [27]:
print('original data: ')
print(df56)

df56[~(df56['value'] == 100)]

original data:
   id  value
0   1     10
1   2     12
2   3     14
3   4     15
4   5     18
5   6     20
6   7     22
7   8    100

   id  value
0   1     10
1   2     12
2   3     14
3   4     15
4   5     18
5   6     20
6   7     22

------------------------------------------------------------------------

### Q64. Sort DataFrame by column values.

> 💡 **Hint:** `df.sort_values("col")`. Use `ascending=False` for descending, `by=["col1","col2"]` for multi-column sort.

In [ ]:
data = {
    'id': [1,2,3,4,5,6,7,8],
    'value': [10, 50, 14, 15, 33, 20, 44, 100]
    }
df56 = pd.DataFrame(data)
print('original data: ')
print(df56)

print('\ndescending: ')
desc = df56.sort_values('id', ascending=False)
print(desc)

print('\nmulti-col sort: ')
print(desc.sort_values(['value','id']))

original data:
   id  value
0   1     10
1   2     50
2   3     14
3   4     15
4   5     33
5   6     20
6   7     44
7   8    100

descending:
   id  value
7   8    100
6   7     44
5   6     20
4   5     33
3   4     15
2   3     14
1   2     50
0   1     10

multi-col sort:
   id  value
0   1     10
2   3     14
3   4     15
5   6     20
4   5     33
6   7     44
1   2     50
7   8    100

------------------------------------------------------------------------

### Q65. Sort DataFrame by index.

> 💡 **Hint:** `df.sort_index()`. Use `axis=1` to sort columns alphabetically.

In [ ]:
data = {
    'no' : [3,1,2],
    'age': [20,30,40],
    'name': ['Rohan', 'Sham', 'Prem']
    }
df65 = pd.DataFrame(data, index=[2,0,1])
print('original data: ')
print(df65)

print('\nsort col alphabetically: ')
print(df65.sort_index(axis=1))

original data:
   no  age   name
2   3   20  Rohan
0   1   30   Sham
1   2   40   Prem

sort col alphabetically:
   age   name  no
2   20  Rohan   3
0   30   Sham   1
1   40   Prem   2

------------------------------------------------------------------------

### Q66. Add calculated column.

> 💡 **Hint:** `df["new"] = df["col1"] * df["col2"]` or use `.assign(new=lambda x: ...)` for chainable operations.

assign() is a DataFrame method used to create new columns or modify existing columns and return a new DataFrame without changing the original one.

In [69]:
data = {
    'product' : ['pen','pencil','rubber','compass'],
    'prc': [20,10,5,100],
    'qty': [50,60,40,50]
    }
df66 = pd.DataFrame(data)
print('original data: ')
print(df66)

df66['ttl'] = df66['prc'] * df66['qty']
print('\nadd new col: \n',df66)

df66 = df66.assign(tax=lambda x: x['ttl'] * 0.18)
print('\nadd another one col: \n',df66)

original data:
   product  prc  qty
0      pen   20   50
1   pencil   10   60
2   rubber    5   40
3  compass  100   50

add new col:
    product  prc  qty   ttl
0      pen   20   50  1000
1   pencil   10   60   600
2   rubber    5   40   200
3  compass  100   50  5000

add another one col:
    product  prc  qty   ttl    tax
0      pen   20   50  1000  180.0
1   pencil   10   60   600  108.0
2   rubber    5   40   200   36.0
3  compass  100   50  5000  900.0

------------------------------------------------------------------------

### Q67. Remove column using `drop()`.

> 💡 **Hint:** `df.drop(columns=["col1","col2"])`. Always use the `columns=` parameter to be explicit.

In [73]:
print("Original DataFrame:")
print(df66)

print("\nAfter dropping columns:")
print(df66.drop(columns=['ttl', 'tax']))

Original DataFrame:
   product  prc  qty   ttl    tax
0      pen   20   50  1000  180.0
1   pencil   10   60   600  108.0
2   rubber    5   40   200   36.0
3  compass  100   50  5000  900.0

After dropping columns:
   product  prc  qty
0      pen   20   50
1   pencil   10   60
2   rubber    5   40
3  compass  100   50

------------------------------------------------------------------------

### Q68. Remove rows using `drop()`.

> 💡 **Hint:** `df.drop(index=[0, 3])` removes rows with those index labels.

In [72]:
print("Original DataFrame:")
print(df66)

print("\nAfter removing rows:")
print(df66.drop(index=[0, 3]))

Original DataFrame:
   product  prc  qty   ttl    tax
0      pen   20   50  1000  180.0
1   pencil   10   60   600  108.0
2   rubber    5   40   200   36.0
3  compass  100   50  5000  900.0

After removing rows:
  product  prc  qty  ttl    tax
1  pencil   10   60  600  108.0
2  rubber    5   40  200   36.0

------------------------------------------------------------------------

### Q69. Use `map()` on a column.

> 💡 **Hint:** `df["col"].map({"a": 1, "b": 2})` substitutes values using a dict. Pass a function for element-wise transformation.

In [74]:

df = pd.DataFrame({
    'no': [1,2,3,4,5],
    'grade': ['A', 'B', 'A', 'C', 'B']
})

df['points'] = df['grade'].map({'A': 4,'B': 3,'C': 2})

print(df)

   no grade  points
0   1     A       4
1   2     B       3
2   3     A       4
3   4     C       2
4   5     B       3

------------------------------------------------------------------------

### Q70. Apply function using `apply()`.

> 💡 **Hint:** `df["col"].apply(func)` for a Series. `df.apply(func, axis=0)` column-wise, `df.apply(func, axis=1)` row-wise.

In [79]:
import numpy as np

data = {
    'no' : [3,1,2],
    'age': [20,30,40]
    }
df70 = pd.DataFrame(data)
print('original data: ')
print(df70)

print('\nfor series:')
print(df70['age'].apply(np.mean))

print('\ncol-wise:')
print(df70.apply(np.mean,axis=0))

print('\nrow-wise:')
print(df70.apply(np.mean,axis=1))

original data:
   no  age
0   3   20
1   1   30
2   2   40

for series:
0    20.0
1    30.0
2    40.0
Name: age, dtype: float64

col-wise:
no      2.0
age    30.0
dtype: float64

row-wise:
0    11.5
1    15.5
2    21.0
dtype: float64

------------------------------------------------------------------------

### Q71. Apply element-wise using `applymap()` / `map()`.

> 💡 **Hint:** In older pandas use `df.applymap(func)`. In pandas ≥ 2.1 use `df.map(func)` for element-wise operations on the entire DataFrame.

In [92]:
print('original data: ')
print(df70)

print('\nelement wise operations: ')
print(df70['age'].map(lambda x: x + 1))

original data:
   no  age
0   3   20
1   1   30
2   2   40

element wise operations:
0    21
1    31
2    41
Name: age, dtype: int64

------------------------------------------------------------------------

### Q72. Chain multiple operations.

> 💡 **Hint:** Use method chaining with `(df.copy().loc[...].sort_values(...)[cols].assign(...).reset_index(drop=True))` — wrap in parentheses for multi-line readability.

In [ ]:
data = {
    'product' : ['pen','pencil','rubber','compass'],
    'prc': [20,10,5,100],
    'qty': [50,60,40,50]
    }
df66 = pd.DataFrame(data)
print('original data: ')
print(df66)

result = (
    df66.copy()
      .loc[lambda x: x['qty'] > 40]
      .sort_values('prc')
      .assign(ttl=lambda x: x['prc'] * x['qty'])
      [['product', 'prc', 'qty', 'ttl']]
      .reset_index(drop=True)
)
print('\nchaining method: ')
print(result)

original data:
   product  prc  qty
0      pen   20   50
1   pencil   10   60
2   rubber    5   40
3  compass  100   50

chaining method:
   product  prc  qty   ttl
0   pencil   10   60   600
1      pen   20   50  1000
2  compass  100   50  5000

------------------------------------------------------------------------

### Q73. Normalize numeric columns (Min-Max).

> 💡 **Hint:** `(df["col"] - df["col"].min()) / (df["col"].max() - df["col"].min())` — result is in range \[0, 1\].

In [112]:
data = {
    'name': ['Rohan', 'Sham', 'Prem', 'Raj'],
    'salary': [25000, 50000, 75000, 100000]
}

df73 = pd.DataFrame(data)

df73['salary_norm'] = ((df73['salary'] - df73['salary'].min()) / (df73['salary'].max() - df73['salary'].min()))

print(df73)

    name  salary  salary_norm
0  Rohan   25000     0.000000
1   Sham   50000     0.333333
2   Prem   75000     0.666667
3    Raj  100000     1.000000

------------------------------------------------------------------------

### Q74. Scale numerical data (Z-score standardization).

> 💡 **Hint:** `(df["col"] - df["col"].mean()) / df["col"].std()` — result has mean=0 and std=1.

In [118]:
data = {
    'name': ['Rohan', 'Sham', 'Prem', 'Raj'],
    'salary': [25000, 50000, 75000, 100000]
}

df74 = pd.DataFrame(data)

print('original data: ')
print(df74)

df74['z_score'] = (df74["salary"] - df74["salary"].mean()) / df74["salary"].std()
print('\nadd col of z-score: ')
print(df74)

original data:
    name  salary
0  Rohan   25000
1   Sham   50000
2   Prem   75000
3    Raj  100000

add col of z-score:
    name  salary   z_score
0  Rohan   25000 -1.161895
1   Sham   50000 -0.387298
2   Prem   75000  0.387298
3    Raj  100000  1.161895

------------------------------------------------------------------------

### Q75. Rank values in a column.

> 💡 **Hint:** `df["col"].rank()` — use `ascending=False` for descending rank, `method="dense"` to avoid gaps.

In [ ]:
data = {
    'name': ['Rohan', 'Sham', 'Prem', 'Raj', 'Jay'],
    'marks': [85, 92, 85, 78, 92]
}

df75 = pd.DataFrame(data)

df75['rank'] = df75['marks'].rank()

df75['rank_desc'] = df75['marks'].rank(ascending=False) #for descending

df75['dense_rank'] = df75['marks'].rank(ascending=False,method='dense') # to avoid gaps

print(df75)

    name  marks  rank  rank_desc  dense_rank
0  Rohan     85   2.5        3.5         2.0
1   Sham     92   4.5        1.5         1.0
2   Prem     85   2.5        3.5         2.0
3    Raj     78   1.0        5.0         3.0
4    Jay     92   4.5        1.5         1.0

------------------------------------------------------------------------

### Q76. Create bins using `cut()`.

> 💡 **Hint:** `pd.cut(df["col"], bins=4)` for equal-width bins or `pd.cut(df["col"], bins=[0,25,50,75,100], labels=["Low","Mid","High","Top"])` for custom intervals.

pd.cut() is used to group continuous numeric values into intervals (bins).

In [129]:
data = {
    'marks': [10, 25, 35, 50, 65, 80, 95]
}

df76 = pd.DataFrame(data)

df76['bin'] = pd.cut(df76['marks'], bins=4)
print('for equal length bins:')
print(df76)

df76['grade'] = pd.cut(df76['marks'],bins=[0, 25, 50, 75, 100],labels=['Low', 'Mid', 'High', 'Top'])
print('\ncustom interval: ')
print(df76)

for equal length bins:
   marks             bin
0     10  (9.915, 31.25]
1     25  (9.915, 31.25]
2     35   (31.25, 52.5]
3     50   (31.25, 52.5]
4     65   (52.5, 73.75]
5     80   (73.75, 95.0]
6     95   (73.75, 95.0]

custom interval:
   marks             bin grade
0     10  (9.915, 31.25]   Low
1     25  (9.915, 31.25]   Low
2     35   (31.25, 52.5]   Mid
3     50   (31.25, 52.5]   Mid
4     65   (52.5, 73.75]  High
5     80   (73.75, 95.0]   Top
6     95   (73.75, 95.0]   Top

------------------------------------------------------------------------

### Q77. Create bins using `qcut()`.

> 💡 **Hint:** `pd.qcut(df["col"], q=4)` for **equal-frequency** (quantile-based) bins. Use `labels=["Q1","Q2","Q3","Q4"]` for named bins.

In [132]:
data = {
    'marks': [10, 20, 30, 40, 50, 60, 70, 80]
}

df77 = pd.DataFrame(data)

df77['equal_freq'] = pd.qcut(df77['marks'],q=4)

df77['quartile'] = pd.qcut(df77['marks'],q=4,labels=['Q1', 'Q2', 'Q3', 'Q4'])

print(df77)

   marks     equal_freq quartile
0     10  (9.999, 27.5]       Q1
1     20  (9.999, 27.5]       Q1
2     30   (27.5, 45.0]       Q2
3     40   (27.5, 45.0]       Q2
4     50   (45.0, 62.5]       Q3
5     60   (45.0, 62.5]       Q3
6     70   (62.5, 80.0]       Q4
7     80   (62.5, 80.0]       Q4

------------------------------------------------------------------------

### Q78. Count unique values.

> 💡 **Hint:** `df["col"].nunique()` for the count, `df["col"].value_counts()` for frequency per unique value.

In [11]:
data = {
    'no': [1,2,3,4,5,6,7,8],
    'marks': [10, 20, 20, 40, 50, 50, 70, 80]
}
df78 = pd.DataFrame(data)
print('counts unique values: ',df78['marks'].nunique())
print('\nfrequency per unique values: \n',df78['marks'].value_counts())

counts unique values:  6

frequency per unique values:
 marks
20    2
50    2
10    1
40    1
70    1
80    1
Name: count, dtype: int64

------------------------------------------------------------------------

### Q79. Replace multiple values at once.

> 💡 **Hint:** `df.replace({"col": {"old1": "new1", "old2": "new2"}})` or use a list: `df.replace(["old1","old2"], "new")`.

In [18]:
print('original data: ')
print(df78)

print('\nafter replace: ')
print(df78.replace({'marks': {10:100, 70:700}}))

print('\nuse a list: ')
print(df78.replace([50,80],400))

original data:
   no  marks
0   1     10
1   2     20
2   3     20
3   4     40
4   5     50
5   6     50
6   7     70
7   8     80

after replace:
   no  marks
0   1    100
1   2     20
2   3     20
3   4     40
4   5     50
5   6     50
6   7    700
7   8     80

use a list:
   no  marks
0   1     10
1   2     20
2   3     20
3   4     40
4   5    400
5   6    400
6   7     70
7   8    400

------------------------------------------------------------------------

### Q80. Create flag column based on condition.

> 💡 **Hint:** `df["flag"] = (df["col"] > threshold).astype(int)` — converts True/False to 1/0. Or use `np.where(condition, 1, 0)`.

In [20]:
import numpy as np

df80 = pd.DataFrame({"score": [45, 85, 22, 90, 60]})

df80["passed_flag1"] = (df80["score"] >= 60).astype(int)

df80["passed_flag2"] = np.where(df80["score"] >= 60, 1, 0)

df80

   score  passed_flag1  passed_flag2
0     45             0             0
1     85             1             1
2     22             0             0
3     90             1             1
4     60             1             1

------------------------------------------------------------------------

## 🔹 Section 5: Iteration, GroupBy & Pivot (Q81–Q100)

------------------------------------------------------------------------

### Q81. Iterate over rows using `iterrows()`.

> 💡 **Hint:** `for idx, row in df.iterrows():` — `idx` is the index label, `row` is a Series with column values.

In [23]:
df81 = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"], "score": [150, 200, 350]
    })

for idx, row in df81.iterrows():
    print(f"Index: {idx} | Name: {row['name']} | Score: {row['score']}")

Index: 0 | Name: Alice | Score: 150
Index: 1 | Name: Bob | Score: 200
Index: 2 | Name: Charlie | Score: 350

------------------------------------------------------------------------

### Q82. Iterate using `itertuples()`.

> 💡 **Hint:** `for row in df.itertuples():` — `row.col_name` accesses values. **Faster** than `iterrows()` due to named tuples.

In [ ]:
df82 = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"], "score": [150, 200, 350]
    })

for row in df82.itertuples():
    print(f"Name: {row.name} | Score: {row.score}")

Name: Alice | Score: 150
Name: Bob | Score: 200
Name: Charlie | Score: 350

------------------------------------------------------------------------

### Q83. Iterate over columns.

> 💡 **Hint:** `for col in df.columns:` then access `df[col]`. Or use `df.items()` which yields `(col_name, Series)` pairs.

In [ ]:
df83 = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"], "score": [150, 200, 350]
    })

for col in df83.columns:
    print(f"Column Name: {col}")
    print(f"data: \n{df83[col]}")
print()

for col_name, col_data in df83.items():
    print(f"Column: {col_name}")
    print(f"Data:\n{col_data}")

Column Name: name
data:
0      Alice
1        Bob
2    Charlie
Name: name, dtype: str
Column Name: score
data:
0    150
1    200
2    350
Name: score, dtype: int64

Column: name
Data:
0      Alice
1        Bob
2    Charlie
Name: name, dtype: str
Column: score
Data:
0    150
1    200
2    350
Name: score, dtype: int64

------------------------------------------------------------------------

### Q84. Avoid iteration using vectorization.

> 💡 **Hint:** Replace `for` loops with direct column operations: `df["new"] = df["a"] * 2 + 1` instead of a loop over rows.

In [60]:
df84 = pd.DataFrame({
    "name": ["Alice", "Bob", "Charlie"], "score": [150, 200, 350]
    })

df84['new'] = df84['score'] * 2 + 1
print(df84)

      name  score  new
0    Alice    150  301
1      Bob    200  401
2  Charlie    350  701

------------------------------------------------------------------------

### Q85. Group data using `groupby()`.

> 💡 **Hint:** `df.groupby("col")["value_col"].mean()` — specify the grouping key and the aggregation in one line.

In [96]:
df85 = pd.DataFrame({
    "department": ["IT", "IT", "HR", "HR", "IT"],
    "team": ["Dev", "Dev", "Recruiting", "Ops", "Ops"],
    "salary": [80000, 90000, 60000, 55000, 75000]
})

print('original data: ')
print(df85)

avg_salary = df85.groupby("department")["salary"].mean()
print('\nmean of salary by department ')
print(avg_salary)

original data:
  department        team  salary
0         IT         Dev   80000
1         IT         Dev   90000
2         HR  Recruiting   60000
3         HR         Ops   55000
4         IT         Ops   75000

mean of salary by department
department
HR    57500.000000
IT    81666.666667
Name: salary, dtype: float64

------------------------------------------------------------------------

### Q86. Calculate sum per group.

> 💡 **Hint:** `df.groupby("col")["value"].sum()` — replace `sum` with any aggregation function.

In [97]:
print('original data: ')
print(df85)

sum_salary = df85.groupby("department")["salary"].sum()
print('\nsum of salary by department ')
print(sum_salary)

original data:
  department        team  salary
0         IT         Dev   80000
1         IT         Dev   90000
2         HR  Recruiting   60000
3         HR         Ops   55000
4         IT         Ops   75000

sum of salary by department
department
HR    115000
IT    245000
Name: salary, dtype: int64

------------------------------------------------------------------------

### Q87. Calculate multiple aggregations.

> 💡 **Hint:** `df.groupby("col").agg({"col1": "mean", "col2": "sum"})` or `df.groupby("col").agg(name=("col","func"))` for named aggregation.

In [98]:
df87 = pd.DataFrame({
    "department": ["HR", "IT", "IT", "HR", "IT"],
    "team": ["Dev", "Recruiting", "Ops", "Ops", "Ops"],
    "salary": [50000, 70000, 80000, 60000, 75000],
    "exp": [3, 4, 6, 3, 2]
})

agg1 = df87.groupby("department").agg({"salary":"sum","exp":"mean"})
print('\nmultiple aggreagtion: ')
print(agg1)

agg2 = df87.groupby("department").agg(exp=("exp","mean"))
print('\nmultiple aggreagtion another way: ')
print(agg2)

multiple aggreagtion:
            salary  exp
department
HR          110000  3.0
IT          225000  4.0

multiple aggreagtion another way:
            exp
department
HR          3.0
IT          4.0

------------------------------------------------------------------------

### Q88. Group by multiple columns.

> 💡 **Hint:** `df.groupby(["col1","col2"])["value"].mean()` — pass a list of column names.

In [ ]:
print('original data: ')
print(df85)

multi_col = df85.groupby(['department','team'])['salary'].mean()
print('\nafter group by:')
print(multi_col)

original data:
  department        team  salary
0         IT         Dev   80000
1         IT         Dev   90000
2         HR  Recruiting   60000
3         HR         Ops   55000
4         IT         Ops   75000

after group by:
department  team
HR          Ops           55000.0
            Recruiting    60000.0
IT          Dev           85000.0
            Ops           75000.0
Name: salary, dtype: float64

------------------------------------------------------------------------

### Q89. Filter grouped data.

> 💡 **Hint:** `df.groupby("col").filter(lambda g: g["value"].mean() > threshold)` — keeps entire groups satisfying the condition.

In [109]:
print('original data: ')
print(df85) 

filter = df85.groupby("department").filter(lambda x: x["salary"].mean() > 70000)
print('\nafter filter: ')
print(filter)

original data:
  department        team  salary
0         IT         Dev   80000
1         IT         Dev   90000
2         HR  Recruiting   60000
3         HR         Ops   55000
4         IT         Ops   75000

after filter:
  department team  salary
0         IT  Dev   80000
1         IT  Dev   90000
4         IT  Ops   75000

------------------------------------------------------------------------

### Q90. Transform grouped data using `transform()`.

> 💡 **Hint:** `df.groupby("col")["value"].transform("mean")` — returns a Series **same size as the original DataFrame** filled with group statistics.

In [111]:
print('original data: ')
print(df85) 

transform = df85.groupby("department")["salary"].transform("mean") 
print('\nafter transform: ')
print(transform)

original data:
  department        team  salary
0         IT         Dev   80000
1         IT         Dev   90000
2         HR  Recruiting   60000
3         HR         Ops   55000
4         IT         Ops   75000

after transform:
0    81666.666667
1    81666.666667
2    57500.000000
3    57500.000000
4    81666.666667
Name: salary, dtype: float64

------------------------------------------------------------------------

### Q91. Apply custom function in groupby.

> 💡 **Hint:** `df.groupby("col")["value"].agg(lambda s: s.max() - s.min())` — pass any function that takes a Series and returns a scalar.

In [112]:
print('original data: ')
print(df85) 

cust_func = df85.groupby("department")["salary"].agg(lambda s: s.max() - s.min())
print('\nafter apply cust func: ')
print(cust_func)

original data:
  department        team  salary
0         IT         Dev   80000
1         IT         Dev   90000
2         HR  Recruiting   60000
3         HR         Ops   55000
4         IT         Ops   75000

after apply cust func:
department
HR     5000
IT    15000
Name: salary, dtype: int64

------------------------------------------------------------------------

### Q92. Create basic pivot table.

> 💡 **Hint:** `pd.pivot_table(df, values="val", index="row_col", columns="col_col", aggfunc="mean")`.

In [127]:
print('original data: ')
print(df85) 

print('\nafter pivot:')
pd.pivot_table(df85,values="salary", index="department", columns='team', aggfunc='mean')

original data:
  department        team  salary
0         IT         Dev   80000
1         IT         Dev   90000
2         HR  Recruiting   60000
3         HR         Ops   55000
4         IT         Ops   75000

after pivot:

team            Dev      Ops  Recruiting
department
HR              NaN  55000.0     60000.0
IT          85000.0  75000.0         NaN

------------------------------------------------------------------------

### Q93. Use multiple aggregation functions in pivot.

> 💡 **Hint:** Pass a list to `aggfunc`: `aggfunc=["mean","max"]` — the result will have a MultiLevel column header.

In [128]:
print('original data: ')
print(df85) 

print('\nafter pivot:')
pd.pivot_table(df85,values="salary", index="department", columns='team', aggfunc=['mean','max'])

original data:
  department        team  salary
0         IT         Dev   80000
1         IT         Dev   90000
2         HR  Recruiting   60000
3         HR         Ops   55000
4         IT         Ops   75000

after pivot:

               mean                          max
team            Dev      Ops Recruiting      Dev      Ops Recruiting
department
HR              NaN  55000.0    60000.0      NaN  55000.0    60000.0
IT          85000.0  75000.0        NaN  90000.0  75000.0        NaN

------------------------------------------------------------------------

### Q94. Handle missing values in pivot tables.

> 💡 **Hint:** Use `fill_value=0` in `pivot_table()` to replace NaN with a specific value.

In [129]:
print('original data: ')
print(df85) 

print('\nafter pivot:')
pd.pivot_table(df85,values="salary", index="department", columns='team', aggfunc=['mean','max'], fill_value=0)

original data:
  department        team  salary
0         IT         Dev   80000
1         IT         Dev   90000
2         HR  Recruiting   60000
3         HR         Ops   55000
4         IT         Ops   75000

after pivot:

               mean                        max
team            Dev      Ops Recruiting    Dev    Ops Recruiting
department
HR              0.0  55000.0    60000.0      0  55000      60000
IT          85000.0  75000.0        0.0  90000  75000          0

------------------------------------------------------------------------

### Q95. Add margins (totals) in pivot tables.

> 💡 **Hint:** `margins=True, margins_name="TOTAL"` in `pivot_table()` adds a summary row and column.

In [135]:
print('original data: ')
print(df85) 

print('\nafter pivot:')
pd.pivot_table(df85,values="salary", index="department", columns='team', aggfunc='sum', margins=True, margins_name='Total', fill_value=0)

original data:
  department        team  salary
0         IT         Dev   80000
1         IT         Dev   90000
2         HR  Recruiting   60000
3         HR         Ops   55000
4         IT         Ops   75000

after pivot:

team           Dev     Ops  Recruiting   Total
department
HR               0   55000       60000  115000
IT          170000   75000           0  245000
Total       170000  130000       60000  360000

------------------------------------------------------------------------

### Q97. Convert DataFrame to pivot format.

> 💡 **Hint:** `df.pivot(index="row_key", columns="col_key", values="value")` — requires **unique** combinations of row/column keys (no aggregation).

In [139]:
# Unique data setup (No duplicates for department + team)
df97 = pd.DataFrame({
    "department": ["IT", "HR", "HR", "IT"],
    "team": ["Dev", "Recruiting", "Ops", "Ops"],
    "salary": [85000, 60000, 55000, 75000]
})

pivoted_df = df97.pivot(index="department", columns="team", values="salary")
print(pivoted_df)

team            Dev      Ops  Recruiting
department
HR              NaN  55000.0     60000.0
IT          85000.0  75000.0         NaN

------------------------------------------------------------------------

### Q98. Compare pivot vs groupby.

> 💡 **Hint:** `groupby()` is more flexible and returns a flat structure. `pivot_table()` gives a 2D grid and handles duplicates with aggregation. `pivot()` does **no aggregation** and fails on duplicates.

In [145]:
print('after groupby: ')
print(df85.groupby(["department", "team"])["salary"].mean())

print('\nafter pivot table: ')
print(df85.pivot_table(index="department", columns="team", values="salary", aggfunc="mean"))

after groupby:
department  team
HR          Ops           55000.0
            Recruiting    60000.0
IT          Dev           85000.0
            Ops           75000.0
Name: salary, dtype: float64

after pivot table:
team            Dev      Ops  Recruiting
department
HR              NaN  55000.0     60000.0
IT          85000.0  75000.0         NaN

------------------------------------------------------------------------

### Q99. Build summary report using pivot table.

> 💡 **Hint:** Combine `pivot_table()` with `margins=True` and `fill_value=0`. Chain `.round(2)` for presentation. Export with `.to_csv()` or `.to_excel()`.

In [147]:
report = df85.pivot_table(index="department",columns="team",values="salary",aggfunc="mean",margins=True,margins_name="Total Company",fill_value=0).round(2)

print("--- SUMMARY REPORT ---")
print(report)


report.to_csv("salary_summary_report.csv")
#report.to_excel("salary_summary_report.xlsx")

--- SUMMARY REPORT ---
team               Dev      Ops  Recruiting  Total Company
department
HR                 0.0  55000.0     60000.0       57500.00
IT             85000.0  75000.0         0.0       81666.67
Total Company  85000.0  65000.0     60000.0       72000.00

------------------------------------------------------------------------

### Q100. Create an end-to-end analysis workflow.

> 💡 **Hint:** Follow this pipeline:
>
> 1.  Load data → 2. Inspect (shape, dtypes, nulls) → 3. Clean (fillna, drop_duplicates) → 4. Feature engineer → 5. GroupBy/pivot analysis → 6. Sort and rank → 7. Export results.

In [192]:
# step 1: Load Data---------------------------------------------------------
df100 = pd.DataFrame({
    'product' : ['pen','pencil','rubber','compass','pen'],
    'prc': [20,10,None,100,30],
    'qty': [50,60,40,50,40],
    'city': ['Pune', 'Mumbai', 'Pune', 'Delhi','Mumbai']
    })
print('dataframe: ')
print(df100)    

# step 2: Inspect(shape, dtypes, nulls)-----------------------------------------
print("\n------ 1. Data Shape ------")
print(df.shape)

print("\n------ 2. Data types ------")
print(df.dtypes)

print("\n--- 3. Data Info & Missing Values ---")
print(df.isnull().sum())

# step 3: clean(fillna, drop_duplicates)-----------------------------------------
clean_df = df100.drop_duplicates()
clean_df['prc'] = clean_df['prc'].fillna(clean_df['prc'].median())
print('\nmedian: ',clean_df['prc'].median())
print("------ 4. clean Dataframe ------")
print(clean_df)

# step 4: feature engineer
clean_df["total"] = clean_df["prc"] * clean_df["qty"]

clean_df["tax"] = clean_df["prc"] * 0.18

clean_df['price_group'] = pd.cut(clean_df['prc'],bins=[0, 10, 20, 50],labels=['Low', 'Medium', 'High'])
print("\n------------ 5. create new col ------------")
print(clean_df)

# step 5: Groupby/pivot analysis-----------------------------------------------
product_sales = (clean_df.groupby('product')['total'].sum().reset_index())
print("\n------------ 6. analysis ---------------")
print('\ni.total sale by product: ')
print(product_sales)

sales_city = (clean_df.groupby('city')['total'].sum().reset_index())
print('\nii.total sale by city: ')
print(sales_city)

pivot = pd.pivot_table(clean_df,values='total',index='city',columns='product',aggfunc='sum',fill_value=0)
print("\n---- iii. Final Aggregated Summary ----")
print(pivot)


# step 6: sort and rank
sort_sales = (clean_df.groupby('product')['total'].sum().reset_index().sort_values('total', ascending=False))

sort_sales['rank'] = (sort_sales['total'].rank(ascending=False,method='dense'))
print("\n--- 7. after sort and rank Summary ---")
print(sort_sales)

# step 7: export results
sort_sales.to_csv("cleaned_emp_data.csv", index=False)
#customer_sales.to_excel('customer_sales.xlsx',index=False)

print("\nWorkflow complete! Reports successfully generated and exported.")

dataframe:
   product    prc  qty    city
0      pen   20.0   50    Pune
1   pencil   10.0   60  Mumbai
2   rubber    NaN   40    Pune
3  compass  100.0   50   Delhi
4      pen   30.0   40  Mumbai

------ 1. Data Shape ------
(4, 4)

------ 2. Data types ------
department            str
team                  str
salary              int64
high_earner_flag    int64
dtype: object

--- 3. Data Info & Missing Values ---
department          0
team                0
salary              0
high_earner_flag    0
dtype: int64

median:  25.0
------ 4. clean Dataframe ------
   product    prc  qty    city
0      pen   20.0   50    Pune
1   pencil   10.0   60  Mumbai
2   rubber   25.0   40    Pune
3  compass  100.0   50   Delhi
4      pen   30.0   40  Mumbai

------------ 5. create new col ------------
   product    prc  qty    city   total   tax price_group
0      pen   20.0   50    Pune  1000.0   3.6      Medium
1   pencil   10.0   60  Mumbai   600.0   1.8         Low
2   rubber   25.0   40    Pune  1000.0   4.5        High
3  compass  100.0   50   Delhi  5000.0  18.0         NaN
4      pen   30.0   40  Mumbai  1200.0   5.4        High

------------ 6. analysis ---------------

i.total sale by product:
   product   total
0  compass  5000.0
1      pen  2200.0
2   pencil   600.0
3   rubber  1000.0

ii.total sale by city:
     city   total
0   Delhi  5000.0
1  Mumbai  1800.0
2    Pune  2000.0

---- iii. Final Aggregated Summary ----
product  compass     pen  pencil  rubber
city
Delhi     5000.0     0.0     0.0     0.0
Mumbai       0.0  1200.0   600.0     0.0
Pune         0.0  1000.0     0.0  1000.0

--- 7. after sort and rank Summary ---
   product   total  rank
0  compass  5000.0   1.0
1      pen  2200.0   2.0
3   rubber  1000.0   3.0
2   pencil   600.0   4.0

Workflow complete! Reports successfully generated and exported.

------------------------------------------------------------------------

*📌 Remember: Try solving without hints first. Look at hints only when genuinely stuck.*  
*⭐ Happy Learning Pandas!*